import { FormEvent, useState } from "react";
import { Link } from "wouter";
import PageSEO from "@/components/PageSEO";

type Health={generatedAt:string;shadow:unknown;announcementSources:{total:number;active:number;errors:number;latest_check:string|null};venues:{verified_configurations:number;latest_verification:string|null}};
type Source={id:string;artist_id:string;artist_name:string;source_type:string;source_url:string;status:string;last_checked_at:string|null;last_changed_at:string|null;last_error:string|null};
export default function TouringAdmin(){
  const [key,setKey]=useState(()=>localStorage.getItem("mexicocharts_admin_key")??""); const [health,setHealth]=useState<Health|null>(null);const[sources,setSources]=useState<Source[]>([]);const[error,setError]=useState("");
  const headers={"X-Admin-Key":key.trim(),"Content-Type":"application/json"};
  async function load(){setError("");try{const[h,s]=await Promise.all([fetch("/api/admin/touring/intelligence/health",{headers}),fetch("/api/admin/touring/intelligence/sources",{headers})]);if(!h.ok||!s.ok)throw new Error(h.status===403||s.status===403?"Clave inválida":"No se pudo cargar");setHealth(await h.json());setSources((await s.json()).sources??[]);localStorage.setItem("mexicocharts_admin_key",key.trim());}catch(e){setError(e instanceof Error?e.message:"Error");}}
  async function addSource(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/admin/touring/intelligence/sources",{method:"POST",headers,body:JSON.stringify({artistId:f.get("artistId"),artistName:f.get("artistName"),sourceType:f.get("sourceType"),sourceUrl:f.get("sourceUrl")})});if(!r.ok){setError("Fuente inválida o no autorizada");return;}event.currentTarget.reset();await load();}
  async function addVenue(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/admin/touring/intelligence/venues",{method:"POST",headers,body:JSON.stringify({venueId:f.get("venueId"),venueName:f.get("venueName"),configuration:f.get("configuration"),capacityLow:Number(f.get("capacityLow")),capacityHigh:Number(f.get("capacityHigh")),sourceUrl:f.get("sourceUrl"),sourceLabel:f.get("sourceLabel"),confidence:f.get("confidence"),verifiedAt:f.get("verifiedAt")})});if(!r.ok){setError("Configuración de recinto inválida");return;}event.currentTarget.reset();await load();}
  const input="h-11 w-full border border-white/10 bg-black px-3 text-sm text-white outline-none focus:border-[#39FF14]";
  return <div className="min-h-screen bg-[#050505] text-white"><PageSEO title="Touring Admin | Mexico Charts" description="Control interno de touring." path="/admin/touring" noindex/><main className="mx-auto max-w-6xl px-6 py-12"><Link href="/admin" className="text-xs font-black uppercase tracking-[.18em] text-[#39FF14]">← Admin</Link><h1 className="mt-6 text-4xl font-black uppercase">Touring Control Center</h1>
    <div className="mt-8 flex gap-2"><input className={input} type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Admin key"/><button onClick={()=>void load()} className="bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Cargar</button></div>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}
    {health&&<section className="mt-8 grid gap-3 md:grid-cols-3"><Stat label="Fuentes activas" value={`${health.announcementSources.active}/${health.announcementSources.total}`}/><Stat label="Errores de fuente" value={String(health.announcementSources.errors)}/><Stat label="Configuraciones verificadas" value={String(health.venues.verified_configurations)}/></section>}
    <section className="mt-10 grid gap-8 lg:grid-cols-2"><form onSubmit={addSource} className="space-y-3 border border-white/10 p-5"><h2 className="font-black uppercase">Agregar fuente autorizada</h2><input name="artistId" required className={input} placeholder="artist-id"/><input name="artistName" required className={input} placeholder="Artista"/><select name="sourceType" className={input}><option value="artist">Artista</option><option value="promoter">Promotor</option><option value="venue">Recinto</option></select><input name="sourceUrl" required type="url" className={input} placeholder="https://fuente-oficial…"/><button className="h-11 bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Guardar fuente</button></form>
      <form onSubmit={addVenue} className="space-y-3 border border-white/10 p-5"><h2 className="font-black uppercase">Capacidad por configuración</h2><input name="venueId" required className={input} placeholder="Ticketmaster venue ID"/><input name="venueName" required className={input} placeholder="Recinto"/><input name="configuration" required className={input} placeholder="Concierto · escenario final"/><div className="grid grid-cols-2 gap-3"><input name="capacityLow" required type="number" min="1" className={input} placeholder="Capacidad baja"/><input name="capacityHigh" required type="number" min="1" className={input} placeholder="Capacidad alta"/></div><input name="sourceUrl" required type="url" className={input} placeholder="https://fuente…"/><input name="sourceLabel" required className={input} placeholder="Nombre de la fuente"/><div className="grid grid-cols-2 gap-3"><select name="confidence" className={input}><option value="high">Alta</option><option value="medium">Media</option><option value="limited">Limitada</option></select><input name="verifiedAt" required type="date" className={input}/></div><button className="h-11 bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Guardar configuración</button></form></section>
    <section className="mt-10"><h2 className="font-black uppercase">Fuentes monitoreadas</h2><div className="mt-4 space-y-2">{sources.map(source=><article key={source.id} className="border border-white/10 p-4 text-xs"><div className="flex flex-wrap justify-between gap-2"><strong>{source.artist_name} · {source.source_type}</strong><span className={source.last_error?"text-red-400":"text-[#39FF14]"}>{source.last_error??source.status}</span></div><a className="mt-2 block break-all text-zinc-500" href={source.source_url} target="_blank" rel="noreferrer">{source.source_url}</a><p className="mt-2 text-zinc-600">Última revisión: {source.last_checked_at?new Date(source.last_checked_at).toLocaleString("es-MX"):"pendiente"}</p></article>)}</div></section>
  </main></div>;
}
function Stat({label,value}:{label:string;value:string}){return <article className="border border-white/10 bg-white/[.02] p-5"><span className="text-[9px] font-black uppercase tracking-[.18em] text-zinc-500">{label}</span><strong className="mt-2 block text-3xl">{value}</strong></article>}
