import { FormEvent, useState } from "react";
import { Link } from "wouter";
import PageSEO from "@/components/PageSEO";

type ShadowRun={id?:number|string;status:string;started_at?:string;finished_at?:string|null;next_run_at?:string|null;fetched_artists?:number;failed_artists?:number;events_observed?:number;snapshots_saved?:number;errors?:string[]};
type TrackedArtist={artistId:string;artistName:string;tourName:string;notBefore:string;matches:number;snapshots:number};
type ShadowHealth={canonical?:boolean;configured:boolean;running:boolean;rosterSize:number;trackedArtists:TrackedArtist[];counts:{events:number;uniqueConcerts:number;snapshotCount:number;snapshots:number;latest_observation:string|null};lastSuccess:ShadowRun|null;latestFailure:ShadowRun|null;nextRunAt:string|null;scheduler:{durable:boolean;limitation:string}};
type Health={generatedAt:string;shadow:ShadowHealth;announcementSources:{total:number;active:number;errors:number;latest_check:string|null};venues:{verified_configurations:number;latest_verification:string|null}};
type Source={id:string;artist_id:string;artist_name:string;source_type:string;source_url:string;status:string;last_checked_at:string|null;last_changed_at:string|null;last_error:string|null};
export default function TouringAdmin(){
  const [key,setKey]=useState(()=>localStorage.getItem("mexicocharts_admin_key")??""); const [health,setHealth]=useState<Health|null>(null);const[sources,setSources]=useState<Source[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const headers={"X-Admin-Key":key.trim(),"Content-Type":"application/json"};
  async function load(){setError("");try{const[h,s]=await Promise.all([fetch("/api/admin/touring/intelligence/health",{headers}),fetch("/api/admin/touring/intelligence/sources",{headers})]);if(!h.ok||!s.ok)throw new Error(h.status===403||s.status===403?"Clave inválida":"No se pudo cargar");setHealth(await h.json());setSources((await s.json()).sources??[]);localStorage.setItem("mexicocharts_admin_key",key.trim());}catch(e){setError(e instanceof Error?e.message:"Error");}}
  async function forceRun(){setError("");setBusy(true);try{const response=await fetch("/api/admin/touring/shadow/force-run",{method:"POST",headers});if(!response.ok)throw new Error("La ejecución canónica falló");await load();}catch(e){setError(e instanceof Error?e.message:"Error");}finally{setBusy(false);}}
  async function addSource(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/admin/touring/intelligence/sources",{method:"POST",headers,body:JSON.stringify({artistId:f.get("artistId"),artistName:f.get("artistName"),sourceType:f.get("sourceType"),sourceUrl:f.get("sourceUrl")})});if(!r.ok){setError("Fuente inválida o no autorizada");return;}event.currentTarget.reset();await load();}
  async function addVenue(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/admin/touring/intelligence/venues",{method:"POST",headers,body:JSON.stringify({venueId:f.get("venueId"),venueName:f.get("venueName"),configuration:f.get("configuration"),capacityLow:Number(f.get("capacityLow")),capacityHigh:Number(f.get("capacityHigh")),sourceUrl:f.get("sourceUrl"),sourceLabel:f.get("sourceLabel"),confidence:f.get("confidence"),verifiedAt:f.get("verifiedAt")})});if(!r.ok){setError("Configuración de recinto inválida");return;}event.currentTarget.reset();await load();}
  const date=(value?:string|null)=>value?new Date(value).toLocaleString("es-MX"):"—";
  const input="h-11 w-full border border-white/10 bg-black px-3 text-sm text-white outline-none focus:border-[#39FF14]";
  return <div className="min-h-screen bg-[#050505] text-white"><PageSEO title="Touring Admin | Mexico Charts" description="Control interno de touring." path="/admin/touring" noindex/><main className="mx-auto max-w-6xl px-6 py-12"><Link href="/admin" className="text-xs font-black uppercase tracking-[.18em] text-[#39FF14]">← Admin</Link><h1 className="mt-6 text-4xl font-black uppercase">Touring Control Center</h1>
    <div className="mt-8 flex flex-col gap-2 sm:flex-row"><input className={input} type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Admin key"/><button onClick={()=>void load()} className="bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Cargar</button></div>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}
    {health&&<><section className="mt-8 grid gap-3 md:grid-cols-3"><Stat label="Último éxito canónico" value={date(health.shadow.lastSuccess?.finished_at)}/><Stat label="Siguiente ejecución" value={date(health.shadow.nextRunAt)}/><Stat label="Conciertos únicos" value={String(health.shadow.counts.uniqueConcerts)}/><Stat label="Snapshots guardados" value={String(health.shadow.counts.snapshotCount)}/><Stat label="Roster configurado" value={`${health.shadow.trackedArtists.length}/${health.shadow.rosterSize}`}/><Stat label="Estado" value={health.shadow.latestFailure&&(!health.shadow.lastSuccess||date(health.shadow.latestFailure.finished_at)>date(health.shadow.lastSuccess.finished_at))?"Revisar":"Saludable"}/></section>
      <section className="mt-8 border border-white/10 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black uppercase">Canonical Touring Command Center</h2><p className="mt-2 max-w-3xl text-sm text-zinc-400">{health.shadow.scheduler.limitation}</p></div><button onClick={()=>void forceRun()} disabled={busy} className="h-11 bg-[#39FF14] px-5 text-xs font-black uppercase text-black disabled:opacity-50">{busy?"Ejecutando…":"Forzar snapshot canónico"}</button></div>{health.shadow.latestFailure&&<p className="mt-4 border-l-2 border-red-500 pl-3 text-sm text-red-300">Último fallo: {date(health.shadow.latestFailure.finished_at)} · {(health.shadow.latestFailure.errors??[]).join("; ")||"sin detalle"}</p>}</section>
      <section className="mt-8 border border-white/10 p-5"><div className="flex items-baseline justify-between gap-4"><h2 className="font-black uppercase">Roster de 10 artistas</h2><span className="text-xs text-zinc-500">Coincidencias / snapshots</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{health.shadow.trackedArtists.map(artist=><article key={artist.artistId} className="flex items-center justify-between border border-white/10 px-4 py-3"><div><strong className="block text-sm">{artist.artistName}</strong><span className="text-xs text-zinc-600">{artist.tourName}</span></div><span className={artist.matches?"text-[#39FF14]":"text-amber-300"}>{artist.matches} / {artist.snapshots}</span></article>)}</div><p className="mt-4 text-xs text-zinc-500">Xavi y Josi Cuen permanecen visibles aunque tengan cero coincidencias.</p></section>
      <section className="mt-8 grid gap-3 md:grid-cols-3"><Stat label="Fuentes activas" value={`${health.announcementSources.active}/${health.announcementSources.total}`}/><Stat label="Errores de fuente" value={String(health.announcementSources.errors)}/><Stat label="Configuraciones verificadas" value={String(health.venues.verified_configurations)}/></section></>}
    <section className="mt-10 grid gap-8 lg:grid-cols-2"><form onSubmit={addSource} className="space-y-3 border border-white/10 p-5"><h2 className="font-black uppercase">Agregar fuente autorizada</h2><input name="artistId" required className={input} placeholder="artist-id"/><input name="artistName" required className={input} placeholder="Artista"/><select name="sourceType" className={input}><option value="artist">Artista</option><option value="promoter">Promotor</option><option value="venue">Recinto</option></select><input name="sourceUrl" required type="url" className={input} placeholder="https://fuente-oficial…"/><button className="h-11 bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Guardar fuente</button></form>
      <form onSubmit={addVenue} className="space-y-3 border border-white/10 p-5"><h2 className="font-black uppercase">Capacidad por configuración</h2><input name="venueId" required className={input} placeholder="Ticketmaster venue ID"/><input name="venueName" required className={input} placeholder="Recinto"/><input name="configuration" required className={input} placeholder="Concierto · escenario final"/><div className="grid grid-cols-2 gap-3"><input name="capacityLow" required type="number" min="1" className={input} placeholder="Capacidad baja"/><input name="capacityHigh" required type="number" min="1" className={input} placeholder="Capacidad alta"/></div><input name="sourceUrl" required type="url" className={input} placeholder="https://fuente…"/><input name="sourceLabel" required className={input} placeholder="Nombre de la fuente"/><div className="grid grid-cols-2 gap-3"><select name="confidence" className={input}><option value="high">Alta</option><option value="medium">Media</option><option value="limited">Limitada</option></select><input name="verifiedAt" required type="date" className={input}/></div><button className="h-11 bg-[#39FF14] px-5 text-xs font-black uppercase text-black">Guardar configuración</button></form></section>
    <section className="mt-10"><h2 className="font-black uppercase">Fuentes monitoreadas</h2><div className="mt-4 space-y-2">{sources.map(source=><article key={source.id} className="border border-white/10 p-4 text-xs"><div className="flex flex-wrap justify-between gap-2"><strong>{source.artist_name} · {source.source_type}</strong><span className={source.last_error?"text-red-400":"text-[#39FF14]"}>{source.last_error??source.status}</span></div><a className="mt-2 block break-all text-zinc-500" href={source.source_url} target="_blank" rel="noreferrer">{source.source_url}</a><p className="mt-2 text-zinc-600">Última revisión: {source.last_checked_at?new Date(source.last_checked_at).toLocaleString("es-MX"):"pendiente"}</p></article>)}</div></section>
  </main></div>;
}
function Stat({label,value}:{label:string;value:string}){return <article className="border border-white/10 bg-white/[.02] p-5"><span className="text-[9px] font-black uppercase tracking-[.18em] text-zinc-500">{label}</span><strong className="mt-2 block text-3xl">{value}</strong></article>}
