// Generated by scripts/generate-peso-monitor-demo.mjs.
// Public platform observations captured 29 August 2026.

export const pesoPlumaMonitorDemo = {
  "capturedAt": "2026-08-29",
  "spotify": {
    "tracks": [
      {
        "type": "track",
        "id": "3qQbCzHBycnDpGskqOWY0E",
        "title": "Ella Baila Sola",
        "spotifyUrl": "https://open.spotify.com/track/3qQbCzHBycnDpGskqOWY0E",
        "total": 1621302922,
        "daily": 492221,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/b1/9b/95/b19b9506-5696-ad86-1c85-d198503adfbf/816144021906_Cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5RqSsdzTNPX1uzkmlHCFvK",
        "title": "QLONA",
        "spotifyUrl": "https://open.spotify.com/track/5RqSsdzTNPX1uzkmlHCFvK",
        "total": 1478462594,
        "daily": 524418,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02d026bf9d7780f6a1267b4d03"
      },
      {
        "type": "track",
        "id": "2Vv6jK9zUGyNppjCy3UI8j",
        "title": "La Bebe - Remix",
        "spotifyUrl": "https://open.spotify.com/track/2Vv6jK9zUGyNppjCy3UI8j",
        "total": 1426786807,
        "daily": 527186,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02778fed2ff7e13909b23d86d3"
      },
      {
        "type": "track",
        "id": "1haJsMtoBhHfvuM7XWuT3W",
        "title": "El Azul",
        "spotifyUrl": "https://open.spotify.com/track/1haJsMtoBhHfvuM7XWuT3W",
        "total": 1021736178,
        "daily": 300556,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/94/22/30/9422301b-2b98-e11e-6f26-e3db43019163/5054197559709.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "7mXuWTczZNxG5EDcjFEuJR",
        "title": "LADY GAGA",
        "spotifyUrl": "https://open.spotify.com/track/7mXuWTczZNxG5EDcjFEuJR",
        "total": 1014848162,
        "daily": 280048,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "1lRtH4FszTrwwlK5gTSbXO",
        "title": "AMG",
        "spotifyUrl": "https://open.spotify.com/track/1lRtH4FszTrwwlK5gTSbXO",
        "total": 910588288,
        "daily": 276180,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e023f6dc5b3d42736bc91068d7b"
      },
      {
        "type": "track",
        "id": "0cNSq9T5l8gZnpY14rsTR2",
        "title": "PRC",
        "spotifyUrl": "https://open.spotify.com/track/0cNSq9T5l8gZnpY14rsTR2",
        "total": 832354624,
        "daily": 190140,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "5lKFO0PrOC9jmOlPEdjHsL",
        "title": "DOS DÍAS",
        "spotifyUrl": "https://open.spotify.com/track/5lKFO0PrOC9jmOlPEdjHsL",
        "total": 810105994,
        "daily": 500078,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0247e9618ef7411438f9c9478b"
      },
      {
        "type": "track",
        "id": "4Nf5EZ40JenjMUKXOiyRU5",
        "title": "NUEVA VIDA",
        "spotifyUrl": "https://open.spotify.com/track/4Nf5EZ40JenjMUKXOiyRU5",
        "total": 717063517,
        "daily": 492087,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "6YWME4xCa5Lm6X1exVMQIC",
        "title": "Por Las Noches",
        "spotifyUrl": "https://open.spotify.com/track/6YWME4xCa5Lm6X1exVMQIC",
        "total": 703122404,
        "daily": 181079,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/b1/a4/60/b1a4600f-10d6-d22a-3500-df55d6e84b2c/3616556081072.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "2aYZaN5SmkRDLsrrV8GkBQ",
        "title": "LA PATRULLA",
        "spotifyUrl": "https://open.spotify.com/track/2aYZaN5SmkRDLsrrV8GkBQ",
        "total": 691725677,
        "daily": 302844,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5GTBdEjZe7zEDp1N0eCZE4",
        "title": "HOLLYWOOD",
        "spotifyUrl": "https://open.spotify.com/track/5GTBdEjZe7zEDp1N0eCZE4",
        "total": 675604922,
        "daily": 760832,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "4oB8Xd7gMlUEtWoD8bmCXW",
        "title": "Morena",
        "spotifyUrl": "https://open.spotify.com/track/4oB8Xd7gMlUEtWoD8bmCXW",
        "total": 637868114,
        "daily": 514162,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/bf/b8/7b/bfb87bdf-9da6-880f-0fca-f74f22135f5b/1963622918315_cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0zNMdrDEs5N0JPQ7RYQZln",
        "title": "QUEMA",
        "spotifyUrl": "https://open.spotify.com/track/0zNMdrDEs5N0JPQ7RYQZln",
        "total": 632342791,
        "daily": 215183,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e025b09c760643ebd02c68baa45"
      },
      {
        "type": "track",
        "id": "3HOKxuTDmNVmIlCIpBiD8m",
        "title": "LAGUNAS",
        "spotifyUrl": "https://open.spotify.com/track/3HOKxuTDmNVmIlCIpBiD8m",
        "total": 625950153,
        "daily": 581909,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "5Fohh8kl8403DSoq4KH7Ll",
        "title": "BELLAKEO",
        "spotifyUrl": "https://open.spotify.com/track/5Fohh8kl8403DSoq4KH7Ll",
        "total": 611817113,
        "daily": 180217,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "7bPp2NmpmyhLJ7zWazAXMu",
        "title": "TULUM",
        "spotifyUrl": "https://open.spotify.com/track/7bPp2NmpmyhLJ7zWazAXMu",
        "total": 548744000,
        "daily": 160982,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "6XaJfhwof7qIgbbXO5tIQI",
        "title": "Igual Que Un Ángel (with Peso Pluma)",
        "spotifyUrl": "https://open.spotify.com/track/6XaJfhwof7qIgbbXO5tIQI",
        "total": 547039675,
        "daily": 313618,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02b968625b03ec59b30b48e9c3"
      },
      {
        "type": "track",
        "id": "5AqiaZwhmC6dIbgWrD5SzV",
        "title": "Peso Pluma: Bzrp Music Sessions, Vol. 55/66",
        "spotifyUrl": "https://open.spotify.com/track/5AqiaZwhmC6dIbgWrD5SzV",
        "total": 532768103,
        "daily": 90816,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e024dad2aa3577403098f33f73a"
      },
      {
        "type": "track",
        "id": "4ygQ5wSuzzNRevVjup1qV2",
        "title": "El Gavilán",
        "spotifyUrl": "https://open.spotify.com/track/4ygQ5wSuzzNRevVjup1qV2",
        "total": 525325219,
        "daily": 73836,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/aa/17/dc/aa17dc82-1930-8921-9d08-c591d9a79453/1963620986347_cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3RA55zrRkyPK8Fd86hrMy8",
        "title": "LUNA",
        "spotifyUrl": "https://open.spotify.com/track/3RA55zrRkyPK8Fd86hrMy8",
        "total": 523165733,
        "daily": 268804,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "3gfSH9aYZbyGjdmbeoWliw",
        "title": "Siempre Pendientes",
        "spotifyUrl": "https://open.spotify.com/track/3gfSH9aYZbyGjdmbeoWliw",
        "total": 504038385,
        "daily": 87749,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02093a2563368d844b2a91306f"
      },
      {
        "type": "track",
        "id": "17js0w8GTkTUFGFM6PYvBd",
        "title": "Igualito a Mi Apá",
        "spotifyUrl": "https://open.spotify.com/track/17js0w8GTkTUFGFM6PYvBd",
        "total": 459857562,
        "daily": 130106,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02c01f2a049a60288bf8966790"
      },
      {
        "type": "track",
        "id": "1RzjXhgnzqb3dMa5852itx",
        "title": "LA PEOPLE",
        "spotifyUrl": "https://open.spotify.com/track/1RzjXhgnzqb3dMa5852itx",
        "total": 453693570,
        "daily": 127992,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "0xGZjxYqcNQ8WqxyeZ4eSN",
        "title": "RUBICON",
        "spotifyUrl": "https://open.spotify.com/track/0xGZjxYqcNQ8WqxyeZ4eSN",
        "total": 446649761,
        "daily": 199593,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "3wlIAXSDtlD9iU8ysld06Z",
        "title": "BIPOLAR",
        "spotifyUrl": "https://open.spotify.com/track/3wlIAXSDtlD9iU8ysld06Z",
        "total": 422657543,
        "daily": 227507,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02e26340898110cbde4cb74e17"
      },
      {
        "type": "track",
        "id": "02cRoSfWU3RJNFyU3o4lhV",
        "title": "SANTAL 33",
        "spotifyUrl": "https://open.spotify.com/track/02cRoSfWU3RJNFyU3o4lhV",
        "total": 403563577,
        "daily": 202051,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5RcxRGvmYai7kpFSfxe5GY",
        "title": "CHANEL",
        "spotifyUrl": "https://open.spotify.com/track/5RcxRGvmYai7kpFSfxe5GY",
        "total": 382158877,
        "daily": 92169,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5a/19/a2/5a19a235-9a79-1fc5-0ab0-e90380342449/196589989758.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "775hCSePn3GW4h9nZ636kq",
        "title": "GAVILÁN II",
        "spotifyUrl": "https://open.spotify.com/track/775hCSePn3GW4h9nZ636kq",
        "total": 380106753,
        "daily": 156991,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "0U4O3GjCZIDXbRUshO1q6P",
        "title": "Ando Enfocado",
        "spotifyUrl": "https://open.spotify.com/track/0U4O3GjCZIDXbRUshO1q6P",
        "total": 379810588,
        "daily": 185470,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/b0/04/72/b00472b3-4b5c-e824-9688-ec52caed23cc/00657467219126_Cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6f8wbdo8KU5ETWJA7lapgS",
        "title": "BYE",
        "spotifyUrl": "https://open.spotify.com/track/6f8wbdo8KU5ETWJA7lapgS",
        "total": 379546786,
        "daily": 149378,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "136BeIIoBGrrU9fI1jbcDR",
        "title": "daño",
        "spotifyUrl": "https://open.spotify.com/track/136BeIIoBGrrU9fI1jbcDR",
        "total": 378556800,
        "daily": 1090598,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "1piak4R3yW4otWWyaSqyCH",
        "title": "El Tsurito",
        "spotifyUrl": "https://open.spotify.com/track/1piak4R3yW4otWWyaSqyCH",
        "total": 373691803,
        "daily": 115947,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02b5422481c51991411aa137d7"
      },
      {
        "type": "track",
        "id": "7bpYjSF1pw7Klp38Y9rJK2",
        "title": "LOS CUADROS",
        "spotifyUrl": "https://open.spotify.com/track/7bpYjSF1pw7Klp38Y9rJK2",
        "total": 362716537,
        "daily": 136856,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0247e9618ef7411438f9c9478b"
      },
      {
        "type": "track",
        "id": "0lc2neV7ZzjZExwCIVG2B3",
        "title": "LAS MORRAS",
        "spotifyUrl": "https://open.spotify.com/track/0lc2neV7ZzjZExwCIVG2B3",
        "total": 347792271,
        "daily": 90229,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "3e32UUqXzrI4g2y5kNZrwC",
        "title": "dopamina",
        "spotifyUrl": "https://open.spotify.com/track/3e32UUqXzrI4g2y5kNZrwC",
        "total": 345249437,
        "daily": 561707,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "3YyTyWfSwAhesGCKpnuRKl",
        "title": "LA PEOPLE II",
        "spotifyUrl": "https://open.spotify.com/track/3YyTyWfSwAhesGCKpnuRKl",
        "total": 313600272,
        "daily": 74996,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5bU6rOWXTwagpjUcGp7I8N",
        "title": "El Belicon",
        "spotifyUrl": "https://open.spotify.com/track/5bU6rOWXTwagpjUcGp7I8N",
        "total": 306733483,
        "daily": 48286,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02cb1eb1ad82a223c988a6a255"
      },
      {
        "type": "track",
        "id": "1uF2sVVCJNWBGSQ2foMWkU",
        "title": "ROMPE LA DOMPE",
        "spotifyUrl": "https://open.spotify.com/track/1uF2sVVCJNWBGSQ2foMWkU",
        "total": 303204073,
        "daily": 70125,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "4yjeRuoVickg1G87LWeRes",
        "title": "ROSA PASTEL",
        "spotifyUrl": "https://open.spotify.com/track/4yjeRuoVickg1G87LWeRes",
        "total": 285592606,
        "daily": 117797,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "1jIirpaACmgb4nTYfywys4",
        "title": "BELANOVA",
        "spotifyUrl": "https://open.spotify.com/track/1jIirpaACmgb4nTYfywys4",
        "total": 274392839,
        "daily": 170586,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "4lzo6zPM2paqyP8oBp3DOs",
        "title": "7-3",
        "spotifyUrl": "https://open.spotify.com/track/4lzo6zPM2paqyP8oBp3DOs",
        "total": 272286676,
        "daily": 428539,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "3GWUv0TDO5E3cHfsxYeptt",
        "title": "TOMMY & PAMELA",
        "spotifyUrl": "https://open.spotify.com/track/3GWUv0TDO5E3cHfsxYeptt",
        "total": 266467815,
        "daily": 134194,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "05tGmdz9dVZ4yGqz4YJdPK",
        "title": "La Intención",
        "spotifyUrl": "https://open.spotify.com/track/05tGmdz9dVZ4yGqz4YJdPK",
        "total": 254035569,
        "daily": 81460,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/07/c0/4d/07c04dcc-6dbe-8b27-530e-ef9ab9a6c50e/196871776172.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4hFLzJh9DxyppZ12USxK6w",
        "title": "UNA BALA",
        "spotifyUrl": "https://open.spotify.com/track/4hFLzJh9DxyppZ12USxK6w",
        "total": 234677269,
        "daily": 198121,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02da17ab0933b7d4700b2665ce"
      },
      {
        "type": "track",
        "id": "0hfXHqWhOpbR9YQmQojDMN",
        "title": "gervonta",
        "spotifyUrl": "https://open.spotify.com/track/0hfXHqWhOpbR9YQmQojDMN",
        "total": 233170253,
        "daily": 119538,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020892be1577c5cdb7eee47fa7"
      },
      {
        "type": "track",
        "id": "2bXJMQZSJND3UYq5mjV4cB",
        "title": "CARNAL",
        "spotifyUrl": "https://open.spotify.com/track/2bXJMQZSJND3UYq5mjV4cB",
        "total": 232007733,
        "daily": 83089,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "3B0swL7Qil9bB7eKzBREBK",
        "title": "VVS",
        "spotifyUrl": "https://open.spotify.com/track/3B0swL7Qil9bB7eKzBREBK",
        "total": 229771711,
        "daily": 69122,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "5jVExEArvISIYu8mamVgfV",
        "title": "LA DURANGO",
        "spotifyUrl": "https://open.spotify.com/track/5jVExEArvISIYu8mamVgfV",
        "total": 204416805,
        "daily": 83837,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "4xv5AneqR0bTokomIPfGyT",
        "title": "MAMI",
        "spotifyUrl": "https://open.spotify.com/track/4xv5AneqR0bTokomIPfGyT",
        "total": 204166797,
        "daily": 127121,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "3PKN5j2dKkzsLbrpcdyzLX",
        "title": "Sentosa",
        "spotifyUrl": "https://open.spotify.com/track/3PKN5j2dKkzsLbrpcdyzLX",
        "total": 200491697,
        "daily": 27995,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a0887b07800af74f7ecb6e1f"
      },
      {
        "type": "track",
        "id": "7uSLF2yhpjLlYBLtyPX3Lb",
        "title": "PLEBADA",
        "spotifyUrl": "https://open.spotify.com/track/7uSLF2yhpjLlYBLtyPX3Lb",
        "total": 199760978,
        "daily": 45846,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/c0/71/34/c0713495-8299-e0cd-afb6-b3dc59c9cb02/197189040207.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "2DXK0YNGSqnaIEX5iaSIoK",
        "title": "RELOJ",
        "spotifyUrl": "https://open.spotify.com/track/2DXK0YNGSqnaIEX5iaSIoK",
        "total": 195999775,
        "daily": 101339,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "2A2x5MZB5OrnnKkVOxx5dp",
        "title": "tu con el",
        "spotifyUrl": "https://open.spotify.com/track/2A2x5MZB5OrnnKkVOxx5dp",
        "total": 194635955,
        "daily": 452541,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "1mF6RkY7x1KsDBZS6cV5f1",
        "title": "EL HECHIZO",
        "spotifyUrl": "https://open.spotify.com/track/1mF6RkY7x1KsDBZS6cV5f1",
        "total": 192457391,
        "daily": 80637,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02c709e6c737fbebcaf05e49a6"
      },
      {
        "type": "track",
        "id": "4dF08DjAjgactxNnsjRod6",
        "title": "Bandida",
        "spotifyUrl": "https://open.spotify.com/track/4dF08DjAjgactxNnsjRod6",
        "total": 191686856,
        "daily": 133816,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022af7247a8f6f33d5a381b6c8"
      },
      {
        "type": "track",
        "id": "7xLfNI4gRNTu6FyXJlzBW5",
        "title": "ni pedo",
        "spotifyUrl": "https://open.spotify.com/track/7xLfNI4gRNTu6FyXJlzBW5",
        "total": 184430876,
        "daily": 397418,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "2ta17XNzvAo7J43BiW0T0Q",
        "title": "BRUCE WAYNE",
        "spotifyUrl": "https://open.spotify.com/track/2ta17XNzvAo7J43BiW0T0Q",
        "total": 178831758,
        "daily": 146489,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5UHK1rtK4MpBGb0KppIYh4",
        "title": "VINO TINTO",
        "spotifyUrl": "https://open.spotify.com/track/5UHK1rtK4MpBGb0KppIYh4",
        "total": 177104919,
        "daily": 85629,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5Q4HTsEGKanxOwL1nYCnhQ",
        "title": "chiclona",
        "spotifyUrl": "https://open.spotify.com/track/5Q4HTsEGKanxOwL1nYCnhQ",
        "total": 168906303,
        "daily": 505250,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028ff0dc6e03af2b4b83e9e274"
      },
      {
        "type": "track",
        "id": "5HiA7W5wYDWi06UZFUluRu",
        "title": "Por las Noches - Remix",
        "spotifyUrl": "https://open.spotify.com/track/5HiA7W5wYDWi06UZFUluRu",
        "total": 162739417,
        "daily": 30133,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/16/98/24/169824d0-de71-50f0-3daf-dcc8686bc361/196589938466.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5LW4Z3Mz4CUliB4b6YyC7K",
        "title": "14 - 14",
        "spotifyUrl": "https://open.spotify.com/track/5LW4Z3Mz4CUliB4b6YyC7K",
        "total": 158830750,
        "daily": 136127,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "7pIRDtTS6V67O4Fm1OpqkO",
        "title": "Pancake",
        "spotifyUrl": "https://open.spotify.com/track/7pIRDtTS6V67O4Fm1OpqkO",
        "total": 156961942,
        "daily": 71465,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028b8c17ec04ac2b9c2ab20d2f"
      },
      {
        "type": "track",
        "id": "27aWzQn0uCuEwHkNlKi1jP",
        "title": "Asquerosamente Rico",
        "spotifyUrl": "https://open.spotify.com/track/27aWzQn0uCuEwHkNlKi1jP",
        "total": 156404463,
        "daily": 114220,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020697c8807331635b1ca25e84"
      },
      {
        "type": "track",
        "id": "6yIlqK2Pye64ZUPFfNzsXy",
        "title": "intro",
        "spotifyUrl": "https://open.spotify.com/track/6yIlqK2Pye64ZUPFfNzsXy",
        "total": 152225569,
        "daily": 147988,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "3CEk3KwDixeCKOVPacup7L",
        "title": "ZAPATA",
        "spotifyUrl": "https://open.spotify.com/track/3CEk3KwDixeCKOVPacup7L",
        "total": 147285173,
        "daily": 87861,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "1ZxJvq28DUmAFZxt9lU7n6",
        "title": "Delivery",
        "spotifyUrl": "https://open.spotify.com/track/1ZxJvq28DUmAFZxt9lU7n6",
        "total": 142891704,
        "daily": 40956,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02ddd7cbb6b1548385fc06f75c"
      },
      {
        "type": "track",
        "id": "0IMJsnmPXXgPyQDbhomx1B",
        "title": "LETAL",
        "spotifyUrl": "https://open.spotify.com/track/0IMJsnmPXXgPyQDbhomx1B",
        "total": 141763196,
        "daily": 451428,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/ff/01/31/ff013190-3956-b78b-2387-4c08ff846c57/ticket.bjhwaepu.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "77phWAt2l34OadUUUqi5ai",
        "title": "Pixelados",
        "spotifyUrl": "https://open.spotify.com/track/77phWAt2l34OadUUUqi5ai",
        "total": 139627290,
        "daily": 34073,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/26/0f/87/260f87c5-c905-d310-f217-abe9e06549a7/1963621844899_cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6WVhjqsmz0ZYuqSXKK3Ezs",
        "title": "Pixeliados",
        "spotifyUrl": "https://open.spotify.com/track/6WVhjqsmz0ZYuqSXKK3Ezs",
        "total": 139531670,
        "daily": 32736,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e020d70614963839704197306fa"
      },
      {
        "type": "track",
        "id": "1tGGJ4SRZnd2H0E2dV05iM",
        "title": "SU CASA",
        "spotifyUrl": "https://open.spotify.com/track/1tGGJ4SRZnd2H0E2dV05iM",
        "total": 132649544,
        "daily": 74080,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "6jUgruwAzfIA3HUQIO3wCR",
        "title": "77",
        "spotifyUrl": "https://open.spotify.com/track/6jUgruwAzfIA3HUQIO3wCR",
        "total": 129039049,
        "daily": 30224,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "track",
        "id": "4BXbjwe562hQ8AzEV5lmPc",
        "title": "putielegante",
        "spotifyUrl": "https://open.spotify.com/track/4BXbjwe562hQ8AzEV5lmPc",
        "total": 123969749,
        "daily": 177379,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "4qfkZtOGVw2BXa05wqXKkV",
        "title": "bckpckbyz",
        "spotifyUrl": "https://open.spotify.com/track/4qfkZtOGVw2BXa05wqXKkV",
        "total": 115522465,
        "daily": 153051,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "7Km1xUI1qByxTCNMf05BZ1",
        "title": "SOLICITADO",
        "spotifyUrl": "https://open.spotify.com/track/7Km1xUI1qByxTCNMf05BZ1",
        "total": 113689159,
        "daily": 73625,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "08nki2OXx4MBVBipAFhste",
        "title": "AMIRI",
        "spotifyUrl": "https://open.spotify.com/track/08nki2OXx4MBVBipAFhste",
        "total": 112278157,
        "daily": 47340,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02e8aa1728ef497b28f14f52cc"
      },
      {
        "type": "track",
        "id": "1qrhpxdnC4nUCyFefPVCDa",
        "title": "SR. SMITH",
        "spotifyUrl": "https://open.spotify.com/track/1qrhpxdnC4nUCyFefPVCDa",
        "total": 111965615,
        "daily": 55634,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "3KTuR5TklU3D3BiBQkWEpI",
        "title": "RARI",
        "spotifyUrl": "https://open.spotify.com/track/3KTuR5TklU3D3BiBQkWEpI",
        "total": 106028450,
        "daily": 68985,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a6c219baa8210e319606f5ce"
      },
      {
        "type": "track",
        "id": "2500EpUpryOBJX0rO8fDuB",
        "title": "A Tu Manera",
        "spotifyUrl": "https://open.spotify.com/track/2500EpUpryOBJX0rO8fDuB",
        "total": 105522357,
        "daily": 35410,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/43/82/1a/43821a98-3888-7c73-cb2d-bcdc2d928c9f/5054197967146.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5c9vvmRxose2Qk8JOxpxrE",
        "title": "ICE",
        "spotifyUrl": "https://open.spotify.com/track/5c9vvmRxose2Qk8JOxpxrE",
        "total": 104533695,
        "daily": 84297,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "6j3PRPNWLutE3CutDzH4uI",
        "title": "HUMO",
        "spotifyUrl": "https://open.spotify.com/track/6j3PRPNWLutE3CutDzH4uI",
        "total": 103269501,
        "daily": 30375,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/ad/45/e0/ad45e0ce-de9f-cf9e-2c37-c15f6e145934/196871999434.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4ix1NGkHZEiVyzoQ6cEVs3",
        "title": "Ex-Special",
        "spotifyUrl": "https://open.spotify.com/track/4ix1NGkHZEiVyzoQ6cEVs3",
        "total": 96320020,
        "daily": 29258,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02e9b89ceb43347701a7d7a327"
      },
      {
        "type": "track",
        "id": "0KVx1aaegvCi9dnQqerJbU",
        "title": "La Melena",
        "spotifyUrl": "https://open.spotify.com/track/0KVx1aaegvCi9dnQqerJbU",
        "total": 88614046,
        "daily": 10603,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1trlpTsQJoBoKQeHGDF72a",
        "title": "Haciendo Memoria",
        "spotifyUrl": "https://open.spotify.com/track/1trlpTsQJoBoKQeHGDF72a",
        "total": 87198919,
        "daily": 122450,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/80/05/3d/80053d02-cf27-7d5b-cd99-4104935886ed/cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "2zq4jvlUHtOk3v5eBLmCje",
        "title": "Lo Que Me Das",
        "spotifyUrl": "https://open.spotify.com/track/2zq4jvlUHtOk3v5eBLmCje",
        "total": 82988053,
        "daily": 13392,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "10Ad7f9fnUaUjZ1bdZWBKr",
        "title": "billete",
        "spotifyUrl": "https://open.spotify.com/track/10Ad7f9fnUaUjZ1bdZWBKr",
        "total": 81300470,
        "daily": 180632,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "6CWwdHPWZDshoiplMtx2Jb",
        "title": "TEKA",
        "spotifyUrl": "https://open.spotify.com/track/6CWwdHPWZDshoiplMtx2Jb",
        "total": 79025736,
        "daily": 24121,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/24/9a/9d/249a9d83-ac75-234d-9717-74ba376357ad/24UMGIM36838.rgb.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4rrGcaA4OqeNty6CXxnfz0",
        "title": "ganga",
        "spotifyUrl": "https://open.spotify.com/track/4rrGcaA4OqeNty6CXxnfz0",
        "total": 78891655,
        "daily": 143729,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028ff0dc6e03af2b4b83e9e274"
      },
      {
        "type": "track",
        "id": "2wr9sstsf2DBgq1BTJr2A9",
        "title": "EN MI MUNDO",
        "spotifyUrl": "https://open.spotify.com/track/2wr9sstsf2DBgq1BTJr2A9",
        "total": 78145726,
        "daily": 65765,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/b7/e3/b5/b7e3b514-ea8b-43ca-79d0-f81fc7ea8f31/198846669885.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0S0pOwYmfbzGgQBYnL9U1j",
        "title": "GIMME A SECOND",
        "spotifyUrl": "https://open.spotify.com/track/0S0pOwYmfbzGgQBYnL9U1j",
        "total": 76393029,
        "daily": 41192,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/01/21/c7/0121c73a-4f0a-de79-204c-81d2561019d5/797885182401_cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3R3HY6mOyGwxJ4dxGgg0Do",
        "title": "OJOS AZULES",
        "spotifyUrl": "https://open.spotify.com/track/3R3HY6mOyGwxJ4dxGgg0Do",
        "total": 76155796,
        "daily": 29839,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02d498621878060e038cf091fa"
      },
      {
        "type": "track",
        "id": "28dxorPKmQwv2KOm7jwtuR",
        "title": "Me Convertí",
        "spotifyUrl": "https://open.spotify.com/track/28dxorPKmQwv2KOm7jwtuR",
        "total": 74660854,
        "daily": 20512,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "track",
        "id": "6cgnliDsVLOjPUcCiUodCt",
        "title": "malibu",
        "spotifyUrl": "https://open.spotify.com/track/6cgnliDsVLOjPUcCiUodCt",
        "total": 74374813,
        "daily": 107627,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "4Hr713a1f4DUOZ7BPuD0PQ",
        "title": "ME ACTIVO",
        "spotifyUrl": "https://open.spotify.com/track/4Hr713a1f4DUOZ7BPuD0PQ",
        "total": 73549001,
        "daily": 48133,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "4GQzSsh8tyuVARj3llp4v9",
        "title": "trucha",
        "spotifyUrl": "https://open.spotify.com/track/4GQzSsh8tyuVARj3llp4v9",
        "total": 66184089,
        "daily": 91343,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "7MgrDeD2asRvec8cJaw4eG",
        "title": "SE TE NOTA",
        "spotifyUrl": "https://open.spotify.com/track/7MgrDeD2asRvec8cJaw4eG",
        "total": 63751142,
        "daily": 35312,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e021458d750b4073726bc9484b3"
      },
      {
        "type": "track",
        "id": "2A802q6kZPas36Fh3nVepA",
        "title": "london",
        "spotifyUrl": "https://open.spotify.com/track/2A802q6kZPas36Fh3nVepA",
        "total": 61306048,
        "daily": 125710,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028ff0dc6e03af2b4b83e9e274"
      },
      {
        "type": "track",
        "id": "7wJvyR1sSY0hmKOkXFlxOG",
        "title": "Sin Yolanda",
        "spotifyUrl": "https://open.spotify.com/track/7wJvyR1sSY0hmKOkXFlxOG",
        "total": 60661629,
        "daily": 26520,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/05/18/d9/0518d9fd-805c-760c-fd65-be3358d1d86d/196922984280_Cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1Cl9wKy0td4uHWe6fbX4AV",
        "title": "Supreme",
        "spotifyUrl": "https://open.spotify.com/track/1Cl9wKy0td4uHWe6fbX4AV",
        "total": 59003222,
        "daily": 50199,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02c4e003935f764a5260c29b83"
      },
      {
        "type": "track",
        "id": "4dUES55SAFKZp4ekMlLHWZ",
        "title": "NO SON KLLE",
        "spotifyUrl": "https://open.spotify.com/track/4dUES55SAFKZp4ekMlLHWZ",
        "total": 57666088,
        "daily": 17377,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02acc066bd17a5cbeb72d9da10"
      },
      {
        "type": "track",
        "id": "06x6rlsG6ZD56K0JFi8yKC",
        "title": "Todo Es Playa",
        "spotifyUrl": "https://open.spotify.com/track/06x6rlsG6ZD56K0JFi8yKC",
        "total": 51689859,
        "daily": 5538,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02eb9563a1a49829221cb10fef"
      },
      {
        "type": "track",
        "id": "2dwUO3wzdasVhl0ULthWPj",
        "title": "El Capi",
        "spotifyUrl": "https://open.spotify.com/track/2dwUO3wzdasVhl0ULthWPj",
        "total": 51178457,
        "daily": 19846,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "track",
        "id": "7KDKBWgusjNgJXX2494v8u",
        "title": "PESO COMPLETO",
        "spotifyUrl": "https://open.spotify.com/track/7KDKBWgusjNgJXX2494v8u",
        "total": 48231231,
        "daily": 13316,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "231mWjDxgJH5OEQFkVIW5p",
        "title": "Peligro",
        "spotifyUrl": "https://open.spotify.com/track/231mWjDxgJH5OEQFkVIW5p",
        "total": 47528772,
        "daily": 19322,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02d10356dbc419ad053e1c23e4"
      },
      {
        "type": "track",
        "id": "26wnP0KsL7VQFR1vbjIVOB",
        "title": "mezcal",
        "spotifyUrl": "https://open.spotify.com/track/26wnP0KsL7VQFR1vbjIVOB",
        "total": 47509915,
        "daily": 59205,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "1gjAVqB8sPT5i96wXUWcJR",
        "title": "LA CHAMBA",
        "spotifyUrl": "https://open.spotify.com/track/1gjAVqB8sPT5i96wXUWcJR",
        "total": 45103772,
        "daily": 6206,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/19/71/ba/1971ba28-4052-2970-e145-65a08e2cf265/197190228724.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0r50cnF7Wo6nVQPhqSYbpc",
        "title": "morras II",
        "spotifyUrl": "https://open.spotify.com/track/0r50cnF7Wo6nVQPhqSYbpc",
        "total": 45078424,
        "daily": 57591,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "7BkpesGJWJqrVKSsIdNLHn",
        "title": "20s",
        "spotifyUrl": "https://open.spotify.com/track/7BkpesGJWJqrVKSsIdNLHn",
        "total": 44769215,
        "daily": 58699,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "2BACqEbfDpPMOO7xhSOz2B",
        "title": "PUT EM IN THE FRIDGE",
        "spotifyUrl": "https://open.spotify.com/track/2BACqEbfDpPMOO7xhSOz2B",
        "total": 44384470,
        "daily": 18298,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "45ewyxF625HzqLCKgZU0tp",
        "title": "Apaga la luz",
        "spotifyUrl": "https://open.spotify.com/track/45ewyxF625HzqLCKgZU0tp",
        "total": 42374707,
        "daily": 59925,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/6b/45/51/6b455110-d4fa-50d6-2258-f8352d76a50c/075679608963.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6HPU2csiZAxNziZbW7jd6Y",
        "title": "Lucky Charms",
        "spotifyUrl": "https://open.spotify.com/track/6HPU2csiZAxNziZbW7jd6Y",
        "total": 40954580,
        "daily": 9204,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0246c5c2f89c37fc6809249316"
      },
      {
        "type": "track",
        "id": "1QxWsh6YFrAhxno50IwtUe",
        "title": "viejo lobo",
        "spotifyUrl": "https://open.spotify.com/track/1QxWsh6YFrAhxno50IwtUe",
        "total": 37618019,
        "daily": 49068,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "track",
        "id": "65C6XLTjQ1sbmldzcUVNi1",
        "title": "Feria en el Sobre",
        "spotifyUrl": "https://open.spotify.com/track/65C6XLTjQ1sbmldzcUVNi1",
        "total": 36900750,
        "daily": 27278,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/95/fc/64/95fc64e5-a3e8-8990-6df0-e5783660bcce/196871225519.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3JU7DUkBDln1FzzuSHc5ec",
        "title": "Desvelada",
        "spotifyUrl": "https://open.spotify.com/track/3JU7DUkBDln1FzzuSHc5ec",
        "total": 36770230,
        "daily": 29842,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e020697c8807331635b1ca25e84"
      },
      {
        "type": "track",
        "id": "0gCxUBn3VimHyJkeapBRHl",
        "title": "La Lleca",
        "spotifyUrl": "https://open.spotify.com/track/0gCxUBn3VimHyJkeapBRHl",
        "total": 36337959,
        "daily": 32552,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022e644e477ad224750287fd6b"
      },
      {
        "type": "track",
        "id": "4Tx0nnFH7oVo3fvVyVeTYv",
        "title": "marianita",
        "spotifyUrl": "https://open.spotify.com/track/4Tx0nnFH7oVo3fvVyVeTYv",
        "total": 36240237,
        "daily": 76582,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028ff0dc6e03af2b4b83e9e274"
      },
      {
        "type": "track",
        "id": "6OhT3i6l8wQnsWJEo2d7vk",
        "title": "CALIFORNIA SUNSET",
        "spotifyUrl": "https://open.spotify.com/track/6OhT3i6l8wQnsWJEo2d7vk",
        "total": 33314193,
        "daily": 36437,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02b3eededd03841503dd3db3a6"
      },
      {
        "type": "track",
        "id": "4prSeUgilnoQ6J5I3iMpQT",
        "title": "Alley Oop",
        "spotifyUrl": "https://open.spotify.com/track/4prSeUgilnoQ6J5I3iMpQT",
        "total": 28883818,
        "daily": 19015,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/8f/33/48/8f33486a-f283-3f4b-9d40-47dcadb142fd/620471.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "2SfL8jCTC7XxKhsD4YhSmV",
        "title": "30 Tiros",
        "spotifyUrl": "https://open.spotify.com/track/2SfL8jCTC7XxKhsD4YhSmV",
        "total": 26373924,
        "daily": 2827,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0211c7bdc66f5e7f86d237ec38"
      },
      {
        "type": "track",
        "id": "15gJuTkHBa9Xri3FJckfnV",
        "title": "La Pluma de Wax",
        "spotifyUrl": "https://open.spotify.com/track/15gJuTkHBa9Xri3FJckfnV",
        "total": 25453685,
        "daily": 4274,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/13/ff/33/13ff336f-4e2b-a010-ea84-bfde76ffb390/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5KHVs1c1Kj0GkCFlNvrO0G",
        "title": "Y Qué?",
        "spotifyUrl": "https://open.spotify.com/track/5KHVs1c1Kj0GkCFlNvrO0G",
        "total": 23727700,
        "daily": 1874,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3HQztiNynPPCCuowUnKoVR",
        "title": "PA NO PENSAR",
        "spotifyUrl": "https://open.spotify.com/track/3HQztiNynPPCCuowUnKoVR",
        "total": 23393540,
        "daily": 9825,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "5PbK9N675eK6ZyvezMgbQR",
        "title": "MALA",
        "spotifyUrl": "https://open.spotify.com/track/5PbK9N675eK6ZyvezMgbQR",
        "total": 23005283,
        "daily": 8596,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "track",
        "id": "31mO4i9sNzomO0dXfSRvnm",
        "title": "Los Pixeliados",
        "spotifyUrl": "https://open.spotify.com/track/31mO4i9sNzomO0dXfSRvnm",
        "total": 22959532,
        "daily": 1686,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0224e85fba218d00e3229eb8ea"
      },
      {
        "type": "track",
        "id": "2r4TBeUkATXJIqQPtwj6C0",
        "title": "Con Dinero Baila El Perro",
        "spotifyUrl": "https://open.spotify.com/track/2r4TBeUkATXJIqQPtwj6C0",
        "total": 22444998,
        "daily": 2466,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "13CvK7typ0qYle19p9Vahn",
        "title": "LAST BREATH (feat. Peso Pluma)",
        "spotifyUrl": "https://open.spotify.com/track/13CvK7typ0qYle19p9Vahn",
        "total": 21593140,
        "daily": 25168,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0295184f6a953569b683ca9a0d"
      },
      {
        "type": "track",
        "id": "5QxIK63R8alaMzvTjuyBkX",
        "title": "Fuentes de Ortiz - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/5QxIK63R8alaMzvTjuyBkX",
        "total": 20584671,
        "daily": 2021,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8e/87/a2/8e87a277-cace-9860-8084-0cbf69adf838/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "2OOmObvtYKotf1WwcqRwe4",
        "title": "La Bebe - David Guetta Remix",
        "spotifyUrl": "https://open.spotify.com/track/2OOmObvtYKotf1WwcqRwe4",
        "total": 19633289,
        "daily": 4595,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02778fed2ff7e13909b23d86d3"
      },
      {
        "type": "track",
        "id": "17UuYgFcpwbvomTtIX54i4",
        "title": "Spiral",
        "spotifyUrl": "https://open.spotify.com/track/17UuYgFcpwbvomTtIX54i4",
        "total": 19310874,
        "daily": 3461,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/7a/12/5d/7a125db6-586e-7c07-f09b-ce604d212b10/197187357086.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4igC2kLaxXZZYnivNQ3rqC",
        "title": "Sembrando",
        "spotifyUrl": "https://open.spotify.com/track/4igC2kLaxXZZYnivNQ3rqC",
        "total": 18610957,
        "daily": 2245,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "track",
        "id": "573KOqctH8YKVj7UU4JBZC",
        "title": "Tiffany",
        "spotifyUrl": "https://open.spotify.com/track/573KOqctH8YKVj7UU4JBZC",
        "total": 17967330,
        "daily": 8665,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0220797b9129aeee434d800128"
      },
      {
        "type": "track",
        "id": "6i6PpqE9lA5eMYTJX57ZhD",
        "title": "UN TRIO",
        "spotifyUrl": "https://open.spotify.com/track/6i6PpqE9lA5eMYTJX57ZhD",
        "total": 16755034,
        "daily": 8021,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02b0f6f3a17b334b2b27c55a6c"
      },
      {
        "type": "track",
        "id": "504nbJ2Wj4eLJiN6r0kvC9",
        "title": "AMIGOS CON DERECHOS",
        "spotifyUrl": "https://open.spotify.com/track/504nbJ2Wj4eLJiN6r0kvC9",
        "total": 16663596,
        "daily": 105252,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e024bc25d5a2470a501a6fbe90c"
      },
      {
        "type": "track",
        "id": "2wGKF4I474KeYzRmJ8CNSv",
        "title": "No Está Fácil",
        "spotifyUrl": "https://open.spotify.com/track/2wGKF4I474KeYzRmJ8CNSv",
        "total": 15767554,
        "daily": 1133,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3GUkooHTVAUeDh3QFavDcp",
        "title": "Les Cuesta",
        "spotifyUrl": "https://open.spotify.com/track/3GUkooHTVAUeDh3QFavDcp",
        "total": 14969696,
        "daily": 1375,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5GlqjDLsp35lSbyn78WfFS",
        "title": "ENCERRONES",
        "spotifyUrl": "https://open.spotify.com/track/5GlqjDLsp35lSbyn78WfFS",
        "total": 13688485,
        "daily": 49246,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02ff4c91d436cfec79c29fc062"
      },
      {
        "type": "track",
        "id": "5k1Io8zsbfSPhUQIod7iP3",
        "title": "INTOCABLE",
        "spotifyUrl": "https://open.spotify.com/track/5k1Io8zsbfSPhUQIod7iP3",
        "total": 13609458,
        "daily": 47671,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e025e212a2c3d548f1319a80a97"
      },
      {
        "type": "track",
        "id": "0VORVyemoOUuiC0eBzSijP",
        "title": "La Encontré",
        "spotifyUrl": "https://open.spotify.com/track/0VORVyemoOUuiC0eBzSijP",
        "total": 13164204,
        "daily": 2603,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "48pQWoo9ZMaceouLTdLlJL",
        "title": "Un Suspiro - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/48pQWoo9ZMaceouLTdLlJL",
        "total": 11498979,
        "daily": 655,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8e/87/a2/8e87a277-cace-9860-8084-0cbf69adf838/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1YfRYkYfl8eRXIusNHvwaj",
        "title": "El Güero",
        "spotifyUrl": "https://open.spotify.com/track/1YfRYkYfl8eRXIusNHvwaj",
        "total": 10899946,
        "daily": 763,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "track",
        "id": "579rIxuKrScE5NlJXrFVsH",
        "title": "El 08 - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/579rIxuKrScE5NlJXrFVsH",
        "total": 10771641,
        "daily": 1760,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/6b/2a/c0/6b2ac0bb-898b-5cd0-e2bd-f281ebf8f513/195336114269.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "57jaFYQpirGBqN9vDdDTW8",
        "title": "El Viejón de la Loma",
        "spotifyUrl": "https://open.spotify.com/track/57jaFYQpirGBqN9vDdDTW8",
        "total": 9170833,
        "daily": 1598,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "track",
        "id": "7JWcatoe9b2QTGk4yb3ZBW",
        "title": "Gente del Cartel",
        "spotifyUrl": "https://open.spotify.com/track/7JWcatoe9b2QTGk4yb3ZBW",
        "total": 8641195,
        "daily": 3412,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/06/f0/32/06f03267-9125-6f9f-e055-ee096edd7214/198588019122.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0ZFiP9xdw3dUkvrbPM1qJP",
        "title": "El AK - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/0ZFiP9xdw3dUkvrbPM1qJP",
        "total": 7341606,
        "daily": 516,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8e/87/a2/8e87a277-cace-9860-8084-0cbf69adf838/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4sHQHZkB2LXWsggJQkcUxO",
        "title": "Relajado Voy",
        "spotifyUrl": "https://open.spotify.com/track/4sHQHZkB2LXWsggJQkcUxO",
        "total": 7305428,
        "daily": 685,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/13/ff/33/13ff336f-4e2b-a010-ea84-bfde76ffb390/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "7MpePLqsFWPjzbZ2Y5ZCgx",
        "title": "Adicción",
        "spotifyUrl": "https://open.spotify.com/track/7MpePLqsFWPjzbZ2Y5ZCgx",
        "total": 6288348,
        "daily": 77996,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/ca/37/4d/ca374de1-29c5-2841-0dcf-f80df149293c/820233456319.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3qwxRAtztIq77Dwd0jCkmP",
        "title": "Jerarquia de Nivel",
        "spotifyUrl": "https://open.spotify.com/track/3qwxRAtztIq77Dwd0jCkmP",
        "total": 6165411,
        "daily": 534,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/88/4e/85/884e850e-e8a0-d020-c5fe-bcae0f7d9252/195266657669.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3SK5PYy8tEkhlxIfYUxgDM",
        "title": "Mil Historias",
        "spotifyUrl": "https://open.spotify.com/track/3SK5PYy8tEkhlxIfYUxgDM",
        "total": 6056112,
        "daily": 2004,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "25TpqB3E7Lv8QSqypjfl5g",
        "title": "Tus Lindos Versos - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/25TpqB3E7Lv8QSqypjfl5g",
        "total": 6021953,
        "daily": 286,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/9b/e4/ae/9be4aecb-00ac-c780-90f7-83bba1f53062/195162890894.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1HXZjZkOgfrVBb7JsK0y1q",
        "title": "Producto De La",
        "spotifyUrl": "https://open.spotify.com/track/1HXZjZkOgfrVBb7JsK0y1q",
        "total": 5984463,
        "daily": 819,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0224e85fba218d00e3229eb8ea"
      },
      {
        "type": "track",
        "id": "24CzvIXYEvOTB9nZWPmVtn",
        "title": "Escuela de la Palma - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/24CzvIXYEvOTB9nZWPmVtn",
        "total": 5844723,
        "daily": 340,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0nQfKIMqHlYXgLQ3qloGYG",
        "title": "Yo Ando Agusto",
        "spotifyUrl": "https://open.spotify.com/track/0nQfKIMqHlYXgLQ3qloGYG",
        "total": 5761043,
        "daily": 372,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/88/4e/85/884e850e-e8a0-d020-c5fe-bcae0f7d9252/195266657669.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6U656W6WTyQKur99ihSybx",
        "title": "fuëgo (feat. Bizarrap, Yeat, Peso Pluma)",
        "spotifyUrl": "https://open.spotify.com/track/6U656W6WTyQKur99ihSybx",
        "total": 5353914,
        "daily": 15719,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020a2a82ed9c4787fc7b54d7d5"
      },
      {
        "type": "track",
        "id": "69ywlo8OoOBWmarW5vjc25",
        "title": "El Petter",
        "spotifyUrl": "https://open.spotify.com/track/69ywlo8OoOBWmarW5vjc25",
        "total": 4603351,
        "daily": 221,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020c3d10039fdf84c390318399"
      },
      {
        "type": "track",
        "id": "2BUl8Rk7fPKQfceDUXe3to",
        "title": "Entre Humo y Huesos",
        "spotifyUrl": "https://open.spotify.com/track/2BUl8Rk7fPKQfceDUXe3to",
        "total": 4560566,
        "daily": 739,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6NYc91HNYaqrCkFqDut1MD",
        "title": "El Ejecutivo - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/6NYc91HNYaqrCkFqDut1MD",
        "total": 4276521,
        "daily": 294,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4kjIrEbm9hUtFPKa3gAB9Z",
        "title": "Entre Aguilas - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/4kjIrEbm9hUtFPKa3gAB9Z",
        "total": 4271361,
        "daily": 235,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "6q4sbXxKDwNiKCZHoonE99",
        "title": "Morena (Remix)",
        "spotifyUrl": "https://open.spotify.com/track/6q4sbXxKDwNiKCZHoonE99",
        "total": 4123872,
        "daily": 2442,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/2b/f6/34/2bf6344f-360d-2aba-2684-e609a1155503/1963623655028_cover.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5McvyUUAOMJOMilH3oT4oH",
        "title": "Jeraqui de Nivel - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/5McvyUUAOMJOMilH3oT4oH",
        "total": 3900139,
        "daily": 164,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/9b/e4/ae/9be4aecb-00ac-c780-90f7-83bba1f53062/195162890894.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "55It0C8RNJrkNqFbhNCfrj",
        "title": "DAYTONA",
        "spotifyUrl": "https://open.spotify.com/track/55It0C8RNJrkNqFbhNCfrj",
        "total": 3855076,
        "daily": 116436,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/2d/97/9d/2d979ddf-1b71-1ce6-7a70-ff67917c27ed/075679576248.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "30KZEXfrwus1jmYKWai9cH",
        "title": "El Chuletas",
        "spotifyUrl": "https://open.spotify.com/track/30KZEXfrwus1jmYKWai9cH",
        "total": 3683145,
        "daily": 612,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3SEu2wnlx0GYx9P9codyNz",
        "title": "NUEVA VIDA - Bandidos Version",
        "spotifyUrl": "https://open.spotify.com/track/3SEu2wnlx0GYx9P9codyNz",
        "total": 3333721,
        "daily": 4804,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022bab30beed9b9b19470e48ed"
      },
      {
        "type": "track",
        "id": "0rcS7yVhxutCsJVd8zn9eM",
        "title": "El Chango - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/0rcS7yVhxutCsJVd8zn9eM",
        "total": 3320012,
        "daily": 322,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3w4vJodMKiRbHUj1mE1t8K",
        "title": "Playera 77 - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/3w4vJodMKiRbHUj1mE1t8K",
        "total": 3076498,
        "daily": 174,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8e/87/a2/8e87a277-cace-9860-8084-0cbf69adf838/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1GyKudEy6DewlE1crF0WIt",
        "title": "La Goma",
        "spotifyUrl": "https://open.spotify.com/track/1GyKudEy6DewlE1crF0WIt",
        "total": 3037566,
        "daily": 2258,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02793e845cc6244757aa8e0e53"
      },
      {
        "type": "track",
        "id": "2QJkXnuTdQt5nfL4kG0KTo",
        "title": "La Melena - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/2QJkXnuTdQt5nfL4kG0KTo",
        "total": 2990315,
        "daily": 690,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1ci8ZFaGfVbN8bgLhJwLad",
        "title": "LAST BREATH (feat. Peso Pluma)",
        "spotifyUrl": "https://open.spotify.com/track/1ci8ZFaGfVbN8bgLhJwLad",
        "total": 2785713,
        "daily": 16676,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02c5b4082a6636bb067532b484"
      },
      {
        "type": "track",
        "id": "58884ZdRpKrylTEQ6oabrV",
        "title": "La Belikiada",
        "spotifyUrl": "https://open.spotify.com/track/58884ZdRpKrylTEQ6oabrV",
        "total": 2585275,
        "daily": 654,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0224e85fba218d00e3229eb8ea"
      },
      {
        "type": "track",
        "id": "2LiRdZZujQ2m1UXsIaKUtV",
        "title": "Pastaillas Pa Olvidar",
        "spotifyUrl": "https://open.spotify.com/track/2LiRdZZujQ2m1UXsIaKUtV",
        "total": 2372627,
        "daily": 523,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/88/4e/85/884e850e-e8a0-d020-c5fe-bcae0f7d9252/195266657669.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "4yvBNLFW047sIozqnh7aMV",
        "title": "El Travieso - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/4yvBNLFW047sIozqnh7aMV",
        "total": 2267752,
        "daily": 196,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0210f085d18ac79091f7f0c517"
      },
      {
        "type": "track",
        "id": "3xd926gxkO9JFc00c0FTud",
        "title": "El Pengüin",
        "spotifyUrl": "https://open.spotify.com/track/3xd926gxkO9JFc00c0FTud",
        "total": 1710120,
        "daily": 520,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/28/fc/a5/28fca535-d399-1ca7-b5e9-b3ef82933900/3617223989646.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "5obBXkG8LsOjTu1YEB4gN5",
        "title": "Apaga la luz (feat. Peso Pluma) – Spotify Sessions",
        "spotifyUrl": "https://open.spotify.com/track/5obBXkG8LsOjTu1YEB4gN5",
        "total": 1643259,
        "daily": 2101,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e021c91d101dc59923897a425d6"
      },
      {
        "type": "track",
        "id": "7K0IG2uBsHy5EFgZNIaHWK",
        "title": "18/02",
        "spotifyUrl": "https://open.spotify.com/track/7K0IG2uBsHy5EFgZNIaHWK",
        "total": 1628990,
        "daily": 450,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/88/4e/85/884e850e-e8a0-d020-c5fe-bcae0f7d9252/195266657669.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "3W3FyFVltvvhfdSWWfVuQp",
        "title": "Lo Que Me Das - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/3W3FyFVltvvhfdSWWfVuQp",
        "total": 1514396,
        "daily": 305,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/6b/2a/c0/6b2ac0bb-898b-5cd0-e2bd-f281ebf8f513/195336114269.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "1NgFyjghXO9ZI3YaRULpF3",
        "title": "La Roca",
        "spotifyUrl": "https://open.spotify.com/track/1NgFyjghXO9ZI3YaRULpF3",
        "total": 1066739,
        "daily": 369,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/88/4e/85/884e850e-e8a0-d020-c5fe-bcae0f7d9252/195266657669.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0v4U8mjDwJmfdFp8HH68Qc",
        "title": "Omnia",
        "spotifyUrl": "https://open.spotify.com/track/0v4U8mjDwJmfdFp8HH68Qc",
        "total": 1064215,
        "daily": 279,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0224e85fba218d00e3229eb8ea"
      },
      {
        "type": "track",
        "id": "7G0yu5nq6Bysoy8nkQSYGl",
        "title": "Relajado Voy",
        "spotifyUrl": "https://open.spotify.com/track/7G0yu5nq6Bysoy8nkQSYGl",
        "total": 924360,
        "daily": 148,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/13/ff/33/13ff336f-4e2b-a010-ea84-bfde76ffb390/artwork.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "69UfUBj0LtDm6EsY8f4vMC",
        "title": "Relajado Voy - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/69UfUBj0LtDm6EsY8f4vMC",
        "total": 768812,
        "daily": 123,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/9b/e4/ae/9be4aecb-00ac-c780-90f7-83bba1f53062/195162890894.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "70Z6Qgh7kEfWk6kYLnA79o",
        "title": "Pluma De Wax - En vivo",
        "spotifyUrl": "https://open.spotify.com/track/70Z6Qgh7kEfWk6kYLnA79o",
        "total": 732165,
        "daily": 452,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/75/1d/d5/751dd5ea-b92f-d9d4-4145-01f19cd576c3/198588008287.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "51BQZgx09nvoZJjUkOLY6x",
        "title": "La Bebe (David Guetta Remix) - Extended Version",
        "spotifyUrl": "https://open.spotify.com/track/51BQZgx09nvoZJjUkOLY6x",
        "total": 679877,
        "daily": 89,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02778fed2ff7e13909b23d86d3"
      },
      {
        "type": "track",
        "id": "6M6UNzXD138cOBvXGV7HyY",
        "title": "Producto de La - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/6M6UNzXD138cOBvXGV7HyY",
        "total": 678995,
        "daily": 120,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/19/28/29/192829ee-2f4b-7153-5094-5213f2edbb19/198391999390.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "7xp910tWhetvPLBs7nxxA1",
        "title": "La Belikiada - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/7xp910tWhetvPLBs7nxxA1",
        "total": 678885,
        "daily": 108,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/9b/e4/ae/9be4aecb-00ac-c780-90f7-83bba1f53062/195162890894.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0iRNMbHwmiwb3gKIFwlJX7",
        "title": "Yo Ando Agusto - En Vivo",
        "spotifyUrl": "https://open.spotify.com/track/0iRNMbHwmiwb3gKIFwlJX7",
        "total": 659829,
        "daily": 119,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/9b/e4/ae/9be4aecb-00ac-c780-90f7-83bba1f53062/195162890894.jpg/600x600bb.jpg"
      },
      {
        "type": "track",
        "id": "0PnPhTToBFbsXX949l1mMn",
        "title": "Teka (with Peso Pluma) - R3HAB Remix",
        "spotifyUrl": "https://open.spotify.com/track/0PnPhTToBFbsXX949l1mMn",
        "total": 642535,
        "daily": 231,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02ac32e8c94f4a9335d5c71362"
      },
      {
        "type": "track",
        "id": "0eYymFdGqgMifdwi8f3ei9",
        "title": "Teka (with Peso Pluma) - CrisMajor Remix",
        "spotifyUrl": "https://open.spotify.com/track/0eYymFdGqgMifdwi8f3ei9",
        "total": 383695,
        "daily": 92,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0245aae8a1079de304338e8580"
      },
      {
        "type": "track",
        "id": "5gHftcoIwPbjQgdPrj8iFn",
        "title": "Teka (with Peso Pluma) - Bontan Remix",
        "spotifyUrl": "https://open.spotify.com/track/5gHftcoIwPbjQgdPrj8iFn",
        "total": 129985,
        "daily": 22,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0262ae015bfc6ddc235a941cb5"
      },
      {
        "type": "track",
        "id": "7vMTLz1753KUQUtQqAVWfd",
        "title": "Producto de LA - En vivo",
        "spotifyUrl": "https://open.spotify.com/track/7vMTLz1753KUQUtQqAVWfd",
        "total": 128263,
        "daily": 125,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/19/28/29/192829ee-2f4b-7153-5094-5213f2edbb19/198391999390.jpg/600x600bb.jpg"
      }
    ],
    "albums": [
      {
        "type": "album",
        "id": "4jox3ip1I39DFC2B7R5qLH",
        "title": "GÉNESIS",
        "spotifyUrl": "https://open.spotify.com/album/4jox3ip1I39DFC2B7R5qLH",
        "total": 7426261146,
        "daily": 3160326,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022fb583ed96f8f35cbf2897ba"
      },
      {
        "type": "album",
        "id": "7DOIN787fF8Jv9KFZEBcW6",
        "title": "GÉNESIS",
        "spotifyUrl": "https://open.spotify.com/album/7DOIN787fF8Jv9KFZEBcW6",
        "total": 5697370251,
        "daily": 2718975,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02e6f540885b43d6f379360b22"
      },
      {
        "type": "album",
        "id": "5kvw1bAOvzJdNi4hdgfaNf",
        "title": "ÉXODO",
        "spotifyUrl": "https://open.spotify.com/album/5kvw1bAOvzJdNi4hdgfaNf",
        "total": 5357897851,
        "daily": 2953424,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e022690127e1d6cd0aa35cc353b"
      },
      {
        "type": "album",
        "id": "7aTDbTfkSxsYEipu8Z4TNl",
        "title": "DINASTÍA (DELUXE)",
        "spotifyUrl": "https://open.spotify.com/album/7aTDbTfkSxsYEipu8Z4TNl",
        "total": 2509056715,
        "daily": 4864657,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e028ff0dc6e03af2b4b83e9e274"
      },
      {
        "type": "album",
        "id": "3kJfKZWulX2oyatVMvDx6a",
        "title": "DINASTÍA",
        "spotifyUrl": "https://open.spotify.com/album/3kJfKZWulX2oyatVMvDx6a",
        "total": 2163712472,
        "daily": 4013386,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a9e6a250ea86a8f387873ef9"
      },
      {
        "type": "album",
        "id": "5aDEezKnOqyQo0qvTFhpkM",
        "title": "DESVELADO",
        "spotifyUrl": "https://open.spotify.com/album/5aDEezKnOqyQo0qvTFhpkM",
        "total": 1621302922,
        "daily": 492221,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02dfddf1cb31b85a6d28b7d91f"
      },
      {
        "type": "album",
        "id": "0FqAaUEyKCyUNFE1uQPZ7i",
        "title": "MAÑANA SERÁ BONITO (BICHOTA SEASON)",
        "spotifyUrl": "https://open.spotify.com/album/0FqAaUEyKCyUNFE1uQPZ7i",
        "total": 1478462594,
        "daily": 524418,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02d026bf9d7780f6a1267b4d03"
      },
      {
        "type": "album",
        "id": "27GWSFRITD8JJcSGMgEfTN",
        "title": "INCÓMODO",
        "spotifyUrl": "https://open.spotify.com/album/27GWSFRITD8JJcSGMgEfTN",
        "total": 1172822531,
        "daily": 636934,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0247e9618ef7411438f9c9478b"
      },
      {
        "type": "album",
        "id": "338NDGMHtB4t5mp8RhMnh3",
        "title": "Mi Vida Mi Muerte",
        "spotifyUrl": "https://open.spotify.com/album/338NDGMHtB4t5mp8RhMnh3",
        "total": 637868114,
        "daily": 514162,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e025c0540f97b3f95e387a9b58e"
      },
      {
        "type": "album",
        "id": "0d9r31X5eeyHWLkYAZIxmE",
        "title": "EL CANTANTE DEL GHETTO",
        "spotifyUrl": "https://open.spotify.com/album/0d9r31X5eeyHWLkYAZIxmE",
        "total": 632342791,
        "daily": 215183,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e025b09c760643ebd02c68baa45"
      },
      {
        "type": "album",
        "id": "6ShIhkhCxgHk9l0vnFBVOK",
        "title": "Efectos Secundarios",
        "spotifyUrl": "https://open.spotify.com/album/6ShIhkhCxgHk9l0vnFBVOK",
        "total": 275976074,
        "daily": 36801,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "album",
        "id": "1m3NgCXFcAW2sFzYbVfWXO",
        "title": "Rico o Muerto, Vol. 1",
        "spotifyUrl": "https://open.spotify.com/album/1m3NgCXFcAW2sFzYbVfWXO",
        "total": 193174693,
        "daily": 144062,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020697c8807331635b1ca25e84"
      },
      {
        "type": "album",
        "id": "0jCDeUgyLX8Jx3fhG8ouiZ",
        "title": "Sembrando",
        "spotifyUrl": "https://open.spotify.com/album/0jCDeUgyLX8Jx3fhG8ouiZ",
        "total": 183831921,
        "daily": 48425,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02941853c4f00b5360b19a3a04"
      },
      {
        "type": "album",
        "id": "2yteT6kCtcAdSbXwPjCM10",
        "title": "Efectos Secundarios",
        "spotifyUrl": "https://open.spotify.com/album/2yteT6kCtcAdSbXwPjCM10",
        "total": 183678883,
        "daily": 25586,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2e/5e/b3/2e5eb33d-3aa8-e17f-aa5d-11d2c8b76e27/3616553726792.jpg/600x600bb.jpg"
      },
      {
        "type": "album",
        "id": "3VVqkkiUqVklgPcC4dnYos",
        "title": "DEPR",
        "spotifyUrl": "https://open.spotify.com/album/3VVqkkiUqVklgPcC4dnYos",
        "total": 141763196,
        "daily": 451428,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02f1b7ee109bd8626cad94f478"
      },
      {
        "type": "album",
        "id": "6CH5CWXWN2X09u7iNuMGN0",
        "title": "Ah Y Que?",
        "spotifyUrl": "https://open.spotify.com/album/6CH5CWXWN2X09u7iNuMGN0",
        "total": 84057528,
        "daily": 11165,
        "compilation": false,
        "artworkUrl": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0224e85fba218d00e3229eb8ea"
      },
      {
        "type": "album",
        "id": "3FPXoHsP3xUjznyOv7J0WS",
        "title": "Disco (En Vivo)",
        "spotifyUrl": "https://open.spotify.com/album/3FPXoHsP3xUjznyOv7J0WS",
        "total": 55210367,
        "daily": 4286,
        "compilation": false,
        "artworkUrl": "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e029294080d04d68c47d1f9c562"
      },
      {
        "type": "album",
        "id": "4EgzAGdJX8tL03haJCiwZy",
        "title": "Disco en Vivo, Vol.2 (En Vivo)",
        "spotifyUrl": "https://open.spotify.com/album/4EgzAGdJX8tL03haJCiwZy",
        "total": 35256721,
        "daily": 4142,
        "compilation": false,
        "artworkUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/33/8e/55/338e5595-16ab-47bb-7c0f-3c1fac9c05b0/artwork.jpg/600x600bb.jpg"
      }
    ]
  },
  "youtube": [
    {
      "id": "fOT0BUpITw8",
      "title": "BELLAKEO (Video Oficial) - Peso Pluma, Anitta",
      "image": "https://i.ytimg.com/vi/fOT0BUpITw8/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=fOT0BUpITw8",
      "views": 755225298,
      "delta": 14623,
      "secondsSincePrevious": 4027,
      "observedAt": "2026-08-29 17:16:27.861443+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 800000000,
      "progress": 94.4
    },
    {
      "id": "qkXIRZKSQ3k",
      "title": "NUEVA VIDA (Lyric Video) - Peso Pluma",
      "image": "https://i.ytimg.com/vi/qkXIRZKSQ3k/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=qkXIRZKSQ3k",
      "views": 656329575,
      "delta": 25773,
      "secondsSincePrevious": 3720,
      "observedAt": "2026-08-29 17:41:29.16069+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 700000000,
      "progress": 93.8
    },
    {
      "id": "rCL8-CiGSmc",
      "title": "Hollywood - Peso Pluma, Estevan Plazola (Video Oficial)",
      "image": "https://i.ytimg.com/vi/rCL8-CiGSmc/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=rCL8-CiGSmc",
      "views": 481069561,
      "delta": 2259086,
      "secondsSincePrevious": 401233,
      "observedAt": "2026-08-29 15:34:11.976068+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 500000000,
      "progress": 96.2
    },
    {
      "id": "kJflWOiAc6I",
      "title": "Peso Pluma, Natanael Cano - PRC (Video Oficial)",
      "image": "https://i.ytimg.com/vi/kJflWOiAc6I/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=kJflWOiAc6I",
      "views": 450593917,
      "delta": 11377,
      "secondsSincePrevious": 4459,
      "observedAt": "2026-08-25 00:13:22.535575+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 500000000,
      "progress": 90.1
    },
    {
      "id": "3Wnso2A4PZE",
      "title": "LADY GAGA (Video Oficial) - Peso Pluma, Gabito Ballesteros, Junior H",
      "image": "https://i.ytimg.com/vi/3Wnso2A4PZE/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=3Wnso2A4PZE",
      "views": 406452427,
      "delta": 9220,
      "secondsSincePrevious": 4464,
      "observedAt": "2026-08-25 00:13:33.035757+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 500000000,
      "progress": 81.3
    },
    {
      "id": "mG_RN0oB4oE",
      "title": "Peso Pluma, Grupo Frontera - TULUM (Video Oficial)",
      "image": "https://i.ytimg.com/vi/mG_RN0oB4oE/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=mG_RN0oB4oE",
      "views": 368689208,
      "delta": 8431,
      "secondsSincePrevious": 4460,
      "observedAt": "2026-08-25 00:13:23.835924+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 400000000,
      "progress": 92.2
    },
    {
      "id": "Fr9rMmMp3mY",
      "title": "LA PATRULLA (Video Oficial) - Peso Pluma, Neton Vega",
      "image": "https://i.ytimg.com/vi/Fr9rMmMp3mY/hqdefault.jpg",
      "url": "https://www.youtube.com/watch?v=Fr9rMmMp3mY",
      "views": 304307666,
      "delta": 8740,
      "secondsSincePrevious": 4029,
      "observedAt": "2026-08-29 17:21:27.460352+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 400000000,
      "progress": 76.1
    },
    {
      "id": "ah2PyhhKqCE",
      "title": "NUEVA VIDA",
      "image": "https://i.ytimg.com/vi/ah2PyhhKqCE/maxresdefault.jpg",
      "url": "https://music.youtube.com/watch?v=ah2PyhhKqCE",
      "views": 276338943,
      "delta": 12430,
      "secondsSincePrevious": 4469,
      "observedAt": "2026-08-25 00:13:48.935662+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 300000000,
      "progress": 92.1
    },
    {
      "id": "4RXnYfHUDJw",
      "title": "El Azul",
      "image": "https://i.ytimg.com/vi/4RXnYfHUDJw/maxresdefault.jpg",
      "url": "https://music.youtube.com/watch?v=4RXnYfHUDJw",
      "views": 223092819,
      "delta": 3718,
      "secondsSincePrevious": 4464,
      "observedAt": "2026-08-25 00:13:33.335497+00",
      "viewsTodayEt": null,
      "views24h": null,
      "milestone": 300000000,
      "progress": 74.4
    }
  ]
} as const;
