import test from 'node:test';import assert from 'node:assert/strict';import {reconcileCatalogEvidence as run} from './catalog-evidence-reconciliation.mjs';
const fixture=()=>{let c={artistKey:'exact',artistName:'Exact Name',spotifyIds:['a'.repeat(22)],identityMappingStatus:'provider_id'},r={audit_captured_at:'2026-09-06T20:00:00Z',source_evidence:{youtube:{protected:'unchanged'}},snapshot:{metric:5},extended:[]};let d=['songs','albums'].map(kind=>({source:{spotifyId:c.spotifyIds[0],kind,httpStatus:200,sha256:'b'.repeat(64),url:`https://kworb.net/spotify/artist/${c.spotifyIds[0]}_${kind}.html`,fetchedAt:'2026-09-06T04:00:00Z'},scope:'complete_captured_kworb_table_not_all_spotify_objects',sourceDate:'2026-09-05',allRowsAccounted:true,expectedCount:1,observedCount:1,items:[{item_type:kind==='songs'?'track':'album',item_key:kind,title:kind,dailyStreams:2,totalStreams:20,artwork_url:null}]}));return {c,r,d};};
test('complete captures apply exact totals; preserve dates, source input and other domains',()=>{let {c,r,d}=fixture(),s=JSON.stringify(r);let x=run(c,r,d,'proof');assert.equal(JSON.stringify(r),s);assert.deepEqual(x.row.snapshot,r.snapshot);assert.deepEqual(x.row.source_evidence.youtube,r.source_evidence.youtube);assert.equal(x.row.served_summary.snapshot_date,'2026-09-05');assert.equal(x.row.served_summary.track_daily_streams,2);assert.equal(x.row.source_evidence.liveCatalogInvestigation.artworkEvidenceApplied,false);});
test('partial stored rows never fabricate a complete denominator',()=>{let {c,r}=fixture();r.kworb_payload={topTracks:[{title:'x'}],trackCount:99};let x=run(c,r,[],'ref');assert.equal(x.row,r);assert.equal(x.manifest.fullCatalogApplied,false);});
test('unknown metrics and mixed source dates stay null',()=>{let {c,r,d}=fixture();d[0].items[0].dailyStreams=null;d[1].sourceDate='2026-08-29';let x=run(c,r,d,'ref');assert.equal(x.row.served_summary.track_daily_streams,null);assert.equal(x.row.served_summary.snapshot_date,null);});
test('identity cases deferred and foreign captures not applied',()=>{let {c,r,d}=fixture();assert.equal(run({...c,identityMappingStatus:'unverified'},r,d,'ref').row,r);assert.equal(run({...c,spotifyIds:['z'.repeat(22)]},r,d,'ref').row,r);});
test('incomplete row accounting rejected',()=>{let {c,r,d}=fixture();d[0].expectedCount=2;assert.throws(()=>run(c,r,d,'ref'));});
test('later capture does not rewrite original evidence clock',()=>{let {c,r,d}=fixture();d[0].source.fetchedAt='2026-09-07T00:00:00Z';assert.equal(run(c,r,d,'ref').manifest.reason,'capture_after_audit_clock');});
test('repeated reconciliation deterministic and input immutable',()=>{let {c,r,d}=fixture();assert.deepEqual(run(c,r,d,'ref'),run(c,r,d,'ref'));});
