import test from 'node:test';import assert from 'node:assert/strict';
import {growthWindows,nativeHistorySatisfies,classifyFindings,createEvidenceEvaluator,GROWTH_SOURCES} from './evidence-pipeline.mjs';
import {reconcileCatalogEvidence} from './catalog-evidence-reconciliation.mjs';
const clock='2026-09-06T20:00:00Z';
const options=()=>({metric:'spotifyMonthlyListeners',artistKey:'exact',sourceKeys:['exact'],clock,
 sources:GROWTH_SOURCES.map(source=>({source,metric:'spotifyMonthlyListeners',artistKey:'exact',sourceKeys:['exact'],capturedAt:clock,reference:'retained-source:123',status:'complete',startDate:'2026-06-01',endDate:'2026-09-06',points:[]}))});
test('growth: exact 7/30/90 observations satisfy all windows without an audit artifact',()=>{const o=options();o.sources[0].points=['2026-09-06','2026-08-30','2026-08-07','2026-06-08'].map(date=>({date,value:10}));assert(growthWindows(o).every(w=>w.state==='satisfied'));});
test('growth: zero observations conclusively absent only after every exact approved source scope is complete',()=>{const w=growthWindows(options());assert(w.every(w=>w.state==='conclusively_no_observations'&&w.absenceEstablished));assert.equal(classifyFindings([{status:'blocked'}]).classification,'C');});
test('growth: known observations but missing baseline distinguish incomplete from absent series',()=>{const o=options();o.sources[0].points=[{date:'2026-09-06',value:10}];assert(growthWindows(o).every(w=>w.state==='observations_incomplete'&&w.absenceEstablished));o.sources[1].status='partial';assert(growthWindows(o).every(w=>w.state==='observations_incomplete'&&!w.absenceEstablished));});
test('growth: missing, partial, foreign-key, future capture or narrow scope cannot prove absence',()=>{for(const change of [o=>o.sources.pop(),o=>o.sources[1].status='partial',o=>o.sources[1].sourceKeys=['other'],o=>o.sources[1].capturedAt='2026-09-07T00:00:00Z',o=>o.sources[1].startDate='2026-09-05']){const o=options();change(o);assert(growthWindows(o).every(w=>!w.absenceEstablished));}});
test('growth: invalid/null values and contradictions are not successful or conclusive evidence',()=>{const o=options();o.sources[0].points=[{date:'2026-09-06',value:null}];assert(growthWindows(o).every(w=>!w.absenceEstablished));o.sources[0].points=[{date:'2026-09-06',value:10},{date:'2026-06-08',value:10}];o.sources[1].points=[{date:'2026-06-08',value:20}];assert.equal(growthWindows(o)[2].state,'undetermined');});
const native=()=>({status:'complete',proof:{kind:'native_intraday_cumulative',sourceTable:'youtube_video_intraday_shadow_snapshots',trustedSourceType:'youtube_api_shadow',timeZone:'America/New_York',rangeDays:90,selection:'last_observation_per_et_date',substitutesForApprovedDailySnapshots:false,buckets:[{scope:'approved',eligibleVideos:2,renderableVideosWithMultipleDates:2,missingTrackedVideos:0,invalidVideoIds:0,unrenderableVideos:0,invalidSelectedPointCount:0}]}});
test('native: complete approved cumulative evidence satisfies cumulative requirement only',()=>{assert(nativeHistorySatisfies(native(),2));assert(!nativeHistorySatisfies(native(),2,'measured_daily_delta'));});
test('native: partial, candidate-only, invalid, wrong source and mismatched denominators never pass',()=>{for(const change of [n=>n.status='invalid',n=>n.proof.buckets[0].scope='candidate_only',n=>n.proof.buckets[0].renderableVideosWithMultipleDates=1,n=>n.proof.buckets[0].missingTrackedVideos=1,n=>n.proof.trustedSourceType='protected_validation',n=>n.proof.substitutesForApprovedDailySnapshots=true]){const n=native();change(n);assert(!nativeHistorySatisfies(n,2));}assert(!nativeHistorySatisfies(native(),3));});
const fixture=()=>{const c={artistKey:'exact',artistName:'Exact',sourceKeys:['exact'],spotifyIds:['a'.repeat(22)],identityMappingStatus:'provider_id'},r={artist_key:'exact',audit_captured_at:clock,source_evidence:{},extended:[]};const d=['songs','albums'].map(kind=>({source:{spotifyId:c.spotifyIds[0],kind,httpStatus:200,sha256:'b'.repeat(64),url:`https://kworb.net/spotify/artist/${c.spotifyIds[0]}_${kind}.html`,fetchedAt:'2026-09-06T04:00:00Z'},scope:'complete_captured_kworb_table_not_all_spotify_objects',sourceDate:'2026-09-05',allRowsAccounted:true,expectedCount:1,observedCount:1,items:[{item_type:kind==='songs'?'track':'album',item_key:kind,title:kind,dailyStreams:2,totalStreams:20,artwork_url:'https://source/image'}]}));return {c,r,d};};
test('catalog: source date differs from acquisition and both retain their meanings',()=>{const {c,r,d}=fixture(),v=reconcileCatalogEvidence(c,r,d,'retained-html');assert.equal(v.row.served_summary.snapshot_date,'2026-09-05');assert.equal(v.row.source_evidence.liveCatalogInvestigation.sourceObservedDate,'2026-09-05');assert.equal(v.row.source_evidence.liveCatalogInvestigation.acquiredAt,'2026-09-06T04:00:00Z');assert(!('observedAt' in v.row.source_evidence.liveCatalogInvestigation));});
test('catalog: unknown/mismatched source date remains unknown; future capture and wrong identity rejected',()=>{const {c,r,d}=fixture();d[0].sourceDate=null;assert.equal(reconcileCatalogEvidence(c,r,d,'r').row.served_summary.snapshot_date,null);d[0].source.fetchedAt='2026-09-07T00:00:00Z';assert(!reconcileCatalogEvidence(c,r,d,'r').manifest.fullCatalogApplied);assert(!reconcileCatalogEvidence({...c,spotifyIds:['z'.repeat(22)]},r,d,'r').manifest.fullCatalogApplied);});
// Integration contract uses a deterministic base stub here. Full frozen-runtime replay is separate.
const baseline={evaluateMonitoringCandidate(c,r){return {artistKey:c.artistKey,artistName:c.artistName,findings:[{code:'full_stream_catalog_unverified',status:'investigation_required'},{code:'live_catalog_fallback_uninvestigated',status:'investigation_required'},{code:'stream_snapshot_stale',status:r.served_summary?.snapshot_date==='2026-09-05'?'repairable':'blocked'}].filter(f=>f.code!=='stream_snapshot_stale'||r.served_summary?.snapshot_date!=='2026-09-05'),sourceEvidence:{catalog:{tracks:1,albums:1,tracksWithArtwork:r.stream_items?.[0]?.artwork_url?1:0,albumsWithArtwork:r.stream_items?.[1]?.artwork_url?1:0}}};}};
function suppliedGrowth(r){r.source_evidence.growthObservations=Object.keys({spotifyMonthlyListeners:1,instagramFollowers:1,tiktokFollowers:1}).flatMap(metric=>options().sources.map(s=>({...s,metric,points:['2026-09-06','2026-08-30','2026-08-07','2026-06-08'].map(date=>({date,value:10}))})));}
test('artifact absence alone does not block exact catalog, artwork and source growth; immutable repeat',()=>{const {c,r,d}=fixture();suppliedGrowth(r);const before=JSON.stringify(r);const e=createEvidenceEvaluator(baseline);const v=e.evaluate(c,r,clock,{documents:d,reference:'retained-html'});assert.equal(v.classification,'A');assert.equal(v.publicEligible,false);assert.equal(JSON.stringify(r),before);assert.deepEqual(e.evaluate(c,r,clock,{documents:d,reference:'retained-html'}),v);assert(!r.source_evidence.catalogCompleteness);});
test('incomplete artwork, unknown source date and missing growth scope cannot become A/B/C',()=>{for(const change of [(r,d)=>d[0].items[0].artwork_url=null,(r,d)=>d[0].sourceDate=null,(r,d)=>delete r.source_evidence.growthObservations]){const {c,r,d}=fixture();suppliedGrowth(r);change(r,d);const v=createEvidenceEvaluator(baseline).evaluate(c,r,clock,{documents:d,reference:'retained'});assert.equal(v.classification,null);assert.equal(v.auditStatus,'incomplete');}});
test('conclusively absent growth can reach C, but missing a source keeps it unresolved',()=>{const {c,r,d}=fixture();suppliedGrowth(r);for(const s of r.source_evidence.growthObservations)if(s.metric==='spotifyMonthlyListeners')s.points=[];const e=createEvidenceEvaluator(baseline);assert.equal(e.evaluate(c,r,clock,{documents:d,reference:'r'}).classification,'C');r.source_evidence.growthObservations=r.source_evidence.growthObservations.filter(s=>s.metric!=='spotifyMonthlyListeners'||s.source!=='verified_compact_history');assert.equal(e.evaluate(c,r,clock,{documents:d,reference:'r'}).classification,null);});

test('absent source date fields serialize as null; fresh fetch cannot repair stale catalog data',()=>{const {c,r,d}=fixture();for(const doc of d)delete doc.sourceDate;assert.equal(reconcileCatalogEvidence(c,r,d,'r').row.served_summary.snapshot_date,null);for(const doc of d)doc.sourceDate='2026-06-01';suppliedGrowth(r);const v=createEvidenceEvaluator(baseline).evaluate(c,r,clock,{documents:d,reference:'r'});assert.equal(v.evidencePipeline.catalog.sourceFresh,false);assert.notEqual(v.classification,'A');});
test('an earlier read cannot certify absence at a later audit clock',()=>{const o=options();o.sources[0].capturedAt='2026-09-05T20:00:00Z';assert(growthWindows(o).every(w=>!w.absenceEstablished));});
test('complete existing evidence with a repairable serving finding remains B',()=>{const {c,r,d}=fixture();suppliedGrowth(r);const b={evaluateMonitoringCandidate(...args){const v=baseline.evaluateMonitoringCandidate(...args);v.findings.push({code:'legacy_source_join_mismatch',status:'repairable'});return v;}};assert.equal(createEvidenceEvaluator(b).evaluate(c,r,clock,{documents:d,reference:'r'}).classification,'B');});
