import test from 'node:test';import assert from 'node:assert/strict';
import {MONITOR_PRO_PRODUCT_CONTRACT as contract,evaluateFounderContract as run,providerArtworkAccepted} from './founder-product-contract.mjs';
const fixture=()=>({e:{artistKey:'exact',artistName:'Exact',identity:{verified:true,coreConflict:false,sourceRef:'identity'},
 audience:Object.fromEntries(['spotifyMonthlyListeners','youtubeSubscribers'].map(k=>[k,{value:0,source:'songstats',identityMatched:true,materializationMatchesSource:true,observedDate:'2026-09-06',sourceRef:k}])),
 catalog:{verified:true,matchedTracks:1,albums:0,hasMeasuredStreams:true,identityMatched:true,sourceRef:'catalog',coverage:'partial'},
 youtube:{approvedVideos:100,approvedObservedVideos:1,relationshipsVerified:true,sourceRef:'approved',freshVideos:0,videosWithMeasuredDelta:0,videosWithComparableHistory:0},
 mexico:{observations:1,genuineMarketEvidence:true,sourceRef:'mx'},
 coreHistories:[{metric:'spotifyMonthlyListeners',identityMatched:true,sameMeasure:true,sourceRef:'history',points:[{date:'2026-09-05',value:0},{date:'2026-09-06',value:0}]}]},
 c:{asOf:'2026-09-06T20:00:00Z',serving:{status:'verified',sourceRef:'actual-response'},youtubeCollector:{paused:true,sourceRef:'founder'},viewer:{verifiedFounder:true,approvedRosterRoute:true}}});
test('minimal genuine data eligible despite missing all former universal gates; valid zero and singles-only catalog',()=>{const {e,c}=fixture();const r=run(e,c);assert.equal(r.artistEligibility.status,'eligible');assert.equal(r.sections.videoViews.freshness,'paused');assert.equal(r.sections.videoDeltas.availability,'unavailable');});
test('paused/stale per-video collector never changes Songstats audience or artist decision',()=>{const {e,c}=fixture();const a=run(e,c);e.youtube.freshVideos=100;const b=run(e,{...c,youtubeCollector:{paused:false}});assert.deepEqual(a.sections.audience,b.sections.audience);assert.deepEqual(a.artistEligibility,b.artistEligibility);});
test('Songstats freshness uses its own dates; a fresh video collector cannot rescue stale audience',()=>{const {e,c}=fixture();e.audience.youtubeSubscribers.observedDate='2026-07-01';e.youtube.freshVideos=100;assert.notEqual(run(e,c).artistEligibility.status,'eligible');});
test('wrong audience source, invalid value, unknown date, incorrect matching or materialization conflict blocks',()=>{for(const change of [r=>r.source='youtube_api',r=>r.value=null,r=>r.value=-1,r=>r.value=Infinity,r=>r.observedDate=null,r=>r.identityMatched=false,r=>r.materializationMatchesSource=false]){const {e,c}=fixture();change(e.audience.youtubeSubscribers);assert.notEqual(run(e,c).artistEligibility.status,'eligible');}});
test('identity conflict, empty catalog, absent approved views and absent genuine Mexico evidence block',()=>{for(const change of [e=>e.identity.coreConflict=true,e=>e.catalog.matchedTracks=0,e=>e.youtube.approvedObservedVideos=0,e=>e.youtube.relationshipsVerified=false,e=>e.mexico.observations=0]){const {e,c}=fixture();change(e);assert.notEqual(run(e,c).artistEligibility.status,'eligible');}});
test('one point, mixed metric/provenance, duplicate dates or invalid values cannot satisfy core history',()=>{for(const change of [h=>h.points.pop(),h=>h.sameMeasure=false,h=>h.identityMatched=false,h=>h.points[1].date=h.points[0].date,h=>h.points[1].value=null]){const {e,c}=fixture();change(e.coreHistories[0]);assert.notEqual(run(e,c).artistEligibility.status,'eligible');}});
test('provider artwork accepted without visual certification; identity and provider attribution remain required',()=>{const x={provider:'spotify',providerObjectId:'track',identityMatchAccepted:true,artworkUrl:'https://provider/image',sourceRef:'provider'};assert(providerArtworkAccepted(x));assert(providerArtworkAccepted({...x,provider:'deezer',artworkEvidenceApplied:false,visuallyReviewed:false}));assert(!providerArtworkAccepted({...x,identityMatchAccepted:false}));assert(!providerArtworkAccepted({...x,provider:'unapproved'}));});
test('missing90-day growth does not suppress7/30-day windows or whole profile',()=>{const {e,c}=fixture();e.growth={spotifyMonthlyListeners:[{days:7,state:'satisfied'},{days:30,state:'satisfied'},{days:90,state:'observations_incomplete'}]};const r=run(e,c);assert.equal(r.artistEligibility.status,'eligible');assert.equal(r.sections.growth.availability,'partial');assert.deepEqual(r.sections.growth.windows.spotifyMonthlyListeners.map(w=>w.availability),['available','available','unavailable']);});
test('serving unknown/failure/repair is separate from missing data and prevents false overall certification',()=>{const {e,c}=fixture();for(const status of ['unknown','failed','repair_required']){const r=run(e,{...c,serving:{status}});assert(r.artistEligibility.dataMinimumsSatisfied);assert.notEqual(r.artistEligibility.status,'eligible');assert.equal(r.artistEligibility.hardBlockers.length+r.artistEligibility.unverifiedHardRequirements.length,1);}});
test('founder inspection independent; ordinary viewer never gets founder entitlement',()=>{const {e,c}=fixture();e.catalog.matchedTracks=0;assert(run(e,c).founderAccess.inspectionAllowed);assert(!run(e,{...c,viewer:{verifiedFounder:false,approvedRosterRoute:true}}).founderAccess.inspectionAllowed);assert(!run(e,{...c,viewer:{verifiedFounder:true,approvedRosterRoute:false}}).founderAccess.inspectionAllowed);});
test('versioned policy immutable, evaluation deterministic, no publication or input mutation',()=>{const {e,c}=fixture(),before=JSON.stringify(e);assert(Object.isFrozen(contract.required));assert.deepEqual(run(e,c),run(e,c));assert.equal(JSON.stringify(e),before);assert.equal(run(e,c).publication.productionEligibilityChanged,false);});
