import { Router, type IRouter } from "express";
import healthRouter from "./health";
import spotifyRouter from "./spotify";
import spotifySyncRouter from "./spotify-sync";
import kworbRouter from "./kworb";
import chartsRouter from "./charts";
import chartsHubRouter from "./charts-hub";
import touringRouter from "./touring";
import artistsRouter from "./artists";
import certificationsRouter from "./certifications";
import imageProxyRouter from "./image-proxy";
import itunesRouter from "./itunes";
import wikiRouter from "./wiki";
import youtubeRouter from "./youtube";
import newsletterRouter from "./newsletter";
import artistDiscoveryRouter from "./artist-discovery";
import songstatsRouter from "./songstats";
import monitoringRouter from "./monitoring";
import accountRouter from "./account";

const router: IRouter = Router();

router.use(healthRouter);
router.use(spotifyRouter);
router.use(spotifySyncRouter);
router.use(kworbRouter);
router.use(chartsRouter);
router.use(chartsHubRouter);
router.use(touringRouter);
router.use(artistsRouter);
router.use(certificationsRouter);
router.use(imageProxyRouter);
router.use(itunesRouter);
router.use(wikiRouter);
router.use(youtubeRouter);
router.use(newsletterRouter);
router.use(artistDiscoveryRouter);
router.use(songstatsRouter);
router.use(monitoringRouter);
router.use(accountRouter);

export default router;
