import { bigint, bigserial, date, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const touringPublicEstimationRuns = pgTable("touring_public_estimation_runs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  shadowRunId: bigint("shadow_run_id", { mode: "number" }),
  triggerReason: text("trigger_reason").notNull(),
  status: text("status").notNull(),
  methodologyVersion: text("methodology_version").notNull(),
  sourceSnapshotCount: integer("source_snapshot_count").notNull().default(0),
  estimatedEventCount: integer("estimated_event_count").notNull().default(0),
  pendingEventCount: integer("pending_event_count").notNull().default(0),
  calculatedAt: timestamp("calculated_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const touringPublicEstimationEvidence = pgTable("touring_public_estimation_evidence", {
  eventId: text("event_id").primaryKey(),
  artistId: text("artist_id").notNull(),
  artistName: text("artist_name").notNull(),
  tourName: text("tour_name").notNull(),
  eventDate: date("event_date").notNull(),
  venueName: text("venue_name").notNull(),
  venueCity: text("venue_city"),
  configuredCapacity: integer("configured_capacity"),
  capacitySource: text("capacity_source"),
  standardPriceMin: numeric("standard_price_min"),
  standardPriceMax: numeric("standard_price_max"),
  standardPriceCurrency: text("standard_price_currency"),
  fxRateMxnPerUsd: numeric("fx_rate_mxn_per_usd"),
  fxRateDate: date("fx_rate_date"),
  offerBreakdown: jsonb("offer_breakdown").notNull().default([]),
  demandSignal: text("demand_signal"),
  comparableKey: text("comparable_key"),
  sourceQuality: jsonb("source_quality").notNull().default({}),
  evidenceTimestamp: timestamp("evidence_timestamp", { withTimezone: true }).notNull().defaultNow(),
  updatedBy: text("updated_by").notNull().default("system"),
  overrideTicketsSold: integer("override_tickets_sold"),
  overrideGrossUsd: numeric("override_gross_usd"),
  overrideAverageTicketUsd: numeric("override_average_ticket_usd"),
  overrideConfidencePercent: numeric("override_confidence_percent"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const touringPublicEstimationEvidenceAudit = pgTable("touring_public_estimation_evidence_audit", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  eventId: text("event_id").notNull(),
  action: text("action").notNull(),
  changedFields: jsonb("changed_fields").notNull().default({}),
  changedBy: text("changed_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const touringPublicEventEstimates = pgTable("touring_public_event_estimates", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  estimationRunId: bigint("estimation_run_id", { mode: "number" }).notNull(),
  eventId: text("event_id").notNull(),
  artistId: text("artist_id").notNull(),
  artistName: text("artist_name").notNull(),
  tourName: text("tour_name").notNull(),
  eventName: text("event_name").notNull(),
  eventDate: date("event_date").notNull(),
  venueName: text("venue_name").notNull(),
  venueCity: text("venue_city"),
  status: text("status").notNull(),
  estimatedTicketsSold: integer("estimated_tickets_sold"),
  estimatedGrossUsd: numeric("estimated_gross_usd"),
  estimatedAverageTicketUsd: numeric("estimated_average_ticket_usd"),
  estimatedCapacityUtilization: numeric("estimated_capacity_utilization"),
  confidencePercent: numeric("confidence_percent"),
  confidenceLabel: text("confidence_label").notNull(),
  evidenceTimestamp: timestamp("evidence_timestamp", { withTimezone: true }),
  methodologyVersion: text("methodology_version").notNull(),
  pendingReasons: jsonb("pending_reasons").notNull().default([]),
  internalUncertainty: jsonb("internal_uncertainty").notNull().default({}),
  sourceQualityInputs: jsonb("source_quality_inputs").notNull().default({}),
  offerBreakdown: jsonb("offer_breakdown").notNull().default([]),
  sourceEventIds: jsonb("source_event_ids").notNull().default([]),
  sourceSnapshotIds: jsonb("source_snapshot_ids").notNull().default([]),
  calculationFingerprint: text("calculation_fingerprint").notNull(),
  calculatedAt: timestamp("calculated_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, table => [
  uniqueIndex("touring_public_event_estimate_run_event_unique").on(table.estimationRunId, table.eventId),
]);

export const touringPublicEstimationAlerts = pgTable("touring_public_estimation_alerts", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  eventId: text("event_id").notNull(),
  artistId: text("artist_id").notNull(),
  artistName: text("artist_name").notNull(),
  alertType: text("alert_type").notNull(),
  fingerprint: text("fingerprint").notNull(),
  previousTicketsSold: integer("previous_tickets_sold"),
  currentTicketsSold: integer("current_tickets_sold"),
  previousGrossUsd: numeric("previous_gross_usd"),
  currentGrossUsd: numeric("current_gross_usd"),
  message: text("message").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, table => [
  uniqueIndex("touring_public_estimation_alert_unique").on(table.eventId, table.alertType, table.fingerprint),
]);